// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.0
// source: pkg/agent/app/mysql/pb/mysql.proto

package mysql

import (
	common "github.com/upmio/unit-operator/pkg/agent/app/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tool int32

const (
	Tool_Xtrabackup Tool = 0
	Tool_Meb        Tool = 1
)

// Enum value maps for Tool.
var (
	Tool_name = map[int32]string{
		0: "Xtrabackup",
		1: "Meb",
	}
	Tool_value = map[string]int32{
		"Xtrabackup": 0,
		"Meb":        1,
	}
)

func (x Tool) Enum() *Tool {
	p := new(Tool)
	*p = x
	return p
}

func (x Tool) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Tool) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_agent_app_mysql_pb_mysql_proto_enumTypes[0].Descriptor()
}

func (Tool) Type() protoreflect.EnumType {
	return &file_pkg_agent_app_mysql_pb_mysql_proto_enumTypes[0]
}

func (x Tool) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Tool.Descriptor instead.
func (Tool) EnumDescriptor() ([]byte, []int) {
	return file_pkg_agent_app_mysql_pb_mysql_proto_rawDescGZIP(), []int{0}
}

type LogicalBackupMode int32

const (
	LogicalBackupMode_Full     LogicalBackupMode = 0
	LogicalBackupMode_Database LogicalBackupMode = 1
	LogicalBackupMode_Table    LogicalBackupMode = 2
)

// Enum value maps for LogicalBackupMode.
var (
	LogicalBackupMode_name = map[int32]string{
		0: "Full",
		1: "Database",
		2: "Table",
	}
	LogicalBackupMode_value = map[string]int32{
		"Full":     0,
		"Database": 1,
		"Table":    2,
	}
)

func (x LogicalBackupMode) Enum() *LogicalBackupMode {
	p := new(LogicalBackupMode)
	*p = x
	return p
}

func (x LogicalBackupMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogicalBackupMode) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_agent_app_mysql_pb_mysql_proto_enumTypes[1].Descriptor()
}

func (LogicalBackupMode) Type() protoreflect.EnumType {
	return &file_pkg_agent_app_mysql_pb_mysql_proto_enumTypes[1]
}

func (x LogicalBackupMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogicalBackupMode.Descriptor instead.
func (LogicalBackupMode) EnumDescriptor() ([]byte, []int) {
	return file_pkg_agent_app_mysql_pb_mysql_proto_rawDescGZIP(), []int{1}
}

type CloneRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SourceCloneUser string                 `protobuf:"bytes,1,opt,name=source_clone_user,json=sourceCloneUser,proto3" json:"source_clone_user,omitempty"`
	SourceHost      string                 `protobuf:"bytes,2,opt,name=source_host,json=sourceHost,proto3" json:"source_host,omitempty"`
	SourcePort      int64                  `protobuf:"varint,3,opt,name=source_port,json=sourcePort,proto3" json:"source_port,omitempty"`
	Username        string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CloneRequest) Reset() {
	*x = CloneRequest{}
	mi := &file_pkg_agent_app_mysql_pb_mysql_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloneRequest) ProtoMessage() {}

func (x *CloneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_app_mysql_pb_mysql_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloneRequest.ProtoReflect.Descriptor instead.
func (*CloneRequest) Descriptor() ([]byte, []int) {
	return file_pkg_agent_app_mysql_pb_mysql_proto_rawDescGZIP(), []int{0}
}

func (x *CloneRequest) GetSourceCloneUser() string {
	if x != nil {
		return x.SourceCloneUser
	}
	return ""
}

func (x *CloneRequest) GetSourceHost() string {
	if x != nil {
		return x.SourceHost
	}
	return ""
}

func (x *CloneRequest) GetSourcePort() int64 {
	if x != nil {
		return x.SourcePort
	}
	return 0
}

func (x *CloneRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type LogicalBackupRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BackupFile        string                 `protobuf:"bytes,1,opt,name=backup_file,json=backupFile,proto3" json:"backup_file,omitempty"`
	Username          string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Database          string                 `protobuf:"bytes,3,opt,name=database,proto3" json:"database,omitempty"`
	Table             string                 `protobuf:"bytes,4,opt,name=table,proto3" json:"table,omitempty"`
	LogicalBackupMode LogicalBackupMode      `protobuf:"varint,5,opt,name=logical_backup_mode,json=logicalBackupMode,proto3,enum=mysql.LogicalBackupMode" json:"logical_backup_mode,omitempty"`
	ObjectStorage     *common.ObjectStorage  `protobuf:"bytes,6,opt,name=object_storage,json=objectStorage,proto3" json:"object_storage,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LogicalBackupRequest) Reset() {
	*x = LogicalBackupRequest{}
	mi := &file_pkg_agent_app_mysql_pb_mysql_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogicalBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicalBackupRequest) ProtoMessage() {}

func (x *LogicalBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_app_mysql_pb_mysql_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicalBackupRequest.ProtoReflect.Descriptor instead.
func (*LogicalBackupRequest) Descriptor() ([]byte, []int) {
	return file_pkg_agent_app_mysql_pb_mysql_proto_rawDescGZIP(), []int{1}
}

func (x *LogicalBackupRequest) GetBackupFile() string {
	if x != nil {
		return x.BackupFile
	}
	return ""
}

func (x *LogicalBackupRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LogicalBackupRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *LogicalBackupRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *LogicalBackupRequest) GetLogicalBackupMode() LogicalBackupMode {
	if x != nil {
		return x.LogicalBackupMode
	}
	return LogicalBackupMode_Full
}

func (x *LogicalBackupRequest) GetObjectStorage() *common.ObjectStorage {
	if x != nil {
		return x.ObjectStorage
	}
	return nil
}

type PhysicalBackupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BackupFile    string                 `protobuf:"bytes,1,opt,name=backup_file,json=backupFile,proto3" json:"backup_file,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Tool          Tool                   `protobuf:"varint,3,opt,name=tool,proto3,enum=mysql.Tool" json:"tool,omitempty"`
	ObjectStorage *common.ObjectStorage  `protobuf:"bytes,4,opt,name=object_storage,json=objectStorage,proto3" json:"object_storage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhysicalBackupRequest) Reset() {
	*x = PhysicalBackupRequest{}
	mi := &file_pkg_agent_app_mysql_pb_mysql_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhysicalBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhysicalBackupRequest) ProtoMessage() {}

func (x *PhysicalBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_app_mysql_pb_mysql_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhysicalBackupRequest.ProtoReflect.Descriptor instead.
func (*PhysicalBackupRequest) Descriptor() ([]byte, []int) {
	return file_pkg_agent_app_mysql_pb_mysql_proto_rawDescGZIP(), []int{2}
}

func (x *PhysicalBackupRequest) GetBackupFile() string {
	if x != nil {
		return x.BackupFile
	}
	return ""
}

func (x *PhysicalBackupRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PhysicalBackupRequest) GetTool() Tool {
	if x != nil {
		return x.Tool
	}
	return Tool_Xtrabackup
}

func (x *PhysicalBackupRequest) GetObjectStorage() *common.ObjectStorage {
	if x != nil {
		return x.ObjectStorage
	}
	return nil
}

type RestoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BackupFile    string                 `protobuf:"bytes,1,opt,name=backup_file,json=backupFile,proto3" json:"backup_file,omitempty"`
	Tool          Tool                   `protobuf:"varint,2,opt,name=tool,proto3,enum=mysql.Tool" json:"tool,omitempty"`
	ObjectStorage *common.ObjectStorage  `protobuf:"bytes,3,opt,name=object_storage,json=objectStorage,proto3" json:"object_storage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreRequest) Reset() {
	*x = RestoreRequest{}
	mi := &file_pkg_agent_app_mysql_pb_mysql_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreRequest) ProtoMessage() {}

func (x *RestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_app_mysql_pb_mysql_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreRequest.ProtoReflect.Descriptor instead.
func (*RestoreRequest) Descriptor() ([]byte, []int) {
	return file_pkg_agent_app_mysql_pb_mysql_proto_rawDescGZIP(), []int{3}
}

func (x *RestoreRequest) GetBackupFile() string {
	if x != nil {
		return x.BackupFile
	}
	return ""
}

func (x *RestoreRequest) GetTool() Tool {
	if x != nil {
		return x.Tool
	}
	return Tool_Xtrabackup
}

func (x *RestoreRequest) GetObjectStorage() *common.ObjectStorage {
	if x != nil {
		return x.ObjectStorage
	}
	return nil
}

type GtidPurgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GtidPurgeRequest) Reset() {
	*x = GtidPurgeRequest{}
	mi := &file_pkg_agent_app_mysql_pb_mysql_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GtidPurgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GtidPurgeRequest) ProtoMessage() {}

func (x *GtidPurgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_app_mysql_pb_mysql_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GtidPurgeRequest.ProtoReflect.Descriptor instead.
func (*GtidPurgeRequest) Descriptor() ([]byte, []int) {
	return file_pkg_agent_app_mysql_pb_mysql_proto_rawDescGZIP(), []int{4}
}

func (x *GtidPurgeRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type SetVariableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetVariableRequest) Reset() {
	*x = SetVariableRequest{}
	mi := &file_pkg_agent_app_mysql_pb_mysql_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetVariableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetVariableRequest) ProtoMessage() {}

func (x *SetVariableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_app_mysql_pb_mysql_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetVariableRequest.ProtoReflect.Descriptor instead.
func (*SetVariableRequest) Descriptor() ([]byte, []int) {
	return file_pkg_agent_app_mysql_pb_mysql_proto_rawDescGZIP(), []int{5}
}

func (x *SetVariableRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetVariableRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SetVariableRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

var File_pkg_agent_app_mysql_pb_mysql_proto protoreflect.FileDescriptor

const file_pkg_agent_app_mysql_pb_mysql_proto_rawDesc = "" +
	"\n" +
	"\"pkg/agent/app/mysql/pb/mysql.proto\x12\x05mysql\x1a$pkg/agent/app/common/pb/common.proto\"\x98\x01\n" +
	"\fCloneRequest\x12*\n" +
	"\x11source_clone_user\x18\x01 \x01(\tR\x0fsourceCloneUser\x12\x1f\n" +
	"\vsource_host\x18\x02 \x01(\tR\n" +
	"sourceHost\x12\x1f\n" +
	"\vsource_port\x18\x03 \x01(\x03R\n" +
	"sourcePort\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\"\x8d\x02\n" +
	"\x14LogicalBackupRequest\x12\x1f\n" +
	"\vbackup_file\x18\x01 \x01(\tR\n" +
	"backupFile\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bdatabase\x18\x03 \x01(\tR\bdatabase\x12\x14\n" +
	"\x05table\x18\x04 \x01(\tR\x05table\x12H\n" +
	"\x13logical_backup_mode\x18\x05 \x01(\x0e2\x18.mysql.LogicalBackupModeR\x11logicalBackupMode\x12<\n" +
	"\x0eobject_storage\x18\x06 \x01(\v2\x15.common.ObjectStorageR\robjectStorage\"\xb3\x01\n" +
	"\x15PhysicalBackupRequest\x12\x1f\n" +
	"\vbackup_file\x18\x01 \x01(\tR\n" +
	"backupFile\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1f\n" +
	"\x04tool\x18\x03 \x01(\x0e2\v.mysql.ToolR\x04tool\x12<\n" +
	"\x0eobject_storage\x18\x04 \x01(\v2\x15.common.ObjectStorageR\robjectStorage\"\x90\x01\n" +
	"\x0eRestoreRequest\x12\x1f\n" +
	"\vbackup_file\x18\x01 \x01(\tR\n" +
	"backupFile\x12\x1f\n" +
	"\x04tool\x18\x02 \x01(\x0e2\v.mysql.ToolR\x04tool\x12<\n" +
	"\x0eobject_storage\x18\x03 \x01(\v2\x15.common.ObjectStorageR\robjectStorage\".\n" +
	"\x10GtidPurgeRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"X\n" +
	"\x12SetVariableRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername*\x1f\n" +
	"\x04Tool\x12\x0e\n" +
	"\n" +
	"Xtrabackup\x10\x00\x12\a\n" +
	"\x03Meb\x10\x01*6\n" +
	"\x11LogicalBackupMode\x12\b\n" +
	"\x04Full\x10\x00\x12\f\n" +
	"\bDatabase\x10\x01\x12\t\n" +
	"\x05Table\x10\x022\xd8\x02\n" +
	"\x0eMysqlOperation\x12+\n" +
	"\x05Clone\x12\x13.mysql.CloneRequest\x1a\r.common.Empty\x12=\n" +
	"\x0ePhysicalBackup\x12\x1c.mysql.PhysicalBackupRequest\x1a\r.common.Empty\x12;\n" +
	"\rLogicalBackup\x12\x1b.mysql.LogicalBackupRequest\x1a\r.common.Empty\x12/\n" +
	"\aRestore\x12\x15.mysql.RestoreRequest\x1a\r.common.Empty\x123\n" +
	"\tGtidPurge\x12\x17.mysql.GtidPurgeRequest\x1a\r.common.Empty\x127\n" +
	"\vSetVariable\x12\x19.mysql.SetVariableRequest\x1a\r.common.EmptyB4Z2github.com/upmio/unit-operator/pkg/agent/app/mysqlb\x06proto3"

var (
	file_pkg_agent_app_mysql_pb_mysql_proto_rawDescOnce sync.Once
	file_pkg_agent_app_mysql_pb_mysql_proto_rawDescData []byte
)

func file_pkg_agent_app_mysql_pb_mysql_proto_rawDescGZIP() []byte {
	file_pkg_agent_app_mysql_pb_mysql_proto_rawDescOnce.Do(func() {
		file_pkg_agent_app_mysql_pb_mysql_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_agent_app_mysql_pb_mysql_proto_rawDesc), len(file_pkg_agent_app_mysql_pb_mysql_proto_rawDesc)))
	})
	return file_pkg_agent_app_mysql_pb_mysql_proto_rawDescData
}

var file_pkg_agent_app_mysql_pb_mysql_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pkg_agent_app_mysql_pb_mysql_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pkg_agent_app_mysql_pb_mysql_proto_goTypes = []any{
	(Tool)(0),                     // 0: mysql.Tool
	(LogicalBackupMode)(0),        // 1: mysql.LogicalBackupMode
	(*CloneRequest)(nil),          // 2: mysql.CloneRequest
	(*LogicalBackupRequest)(nil),  // 3: mysql.LogicalBackupRequest
	(*PhysicalBackupRequest)(nil), // 4: mysql.PhysicalBackupRequest
	(*RestoreRequest)(nil),        // 5: mysql.RestoreRequest
	(*GtidPurgeRequest)(nil),      // 6: mysql.GtidPurgeRequest
	(*SetVariableRequest)(nil),    // 7: mysql.SetVariableRequest
	(*common.ObjectStorage)(nil),  // 8: common.ObjectStorage
	(*common.Empty)(nil),          // 9: common.Empty
}
var file_pkg_agent_app_mysql_pb_mysql_proto_depIdxs = []int32{
	1,  // 0: mysql.LogicalBackupRequest.logical_backup_mode:type_name -> mysql.LogicalBackupMode
	8,  // 1: mysql.LogicalBackupRequest.object_storage:type_name -> common.ObjectStorage
	0,  // 2: mysql.PhysicalBackupRequest.tool:type_name -> mysql.Tool
	8,  // 3: mysql.PhysicalBackupRequest.object_storage:type_name -> common.ObjectStorage
	0,  // 4: mysql.RestoreRequest.tool:type_name -> mysql.Tool
	8,  // 5: mysql.RestoreRequest.object_storage:type_name -> common.ObjectStorage
	2,  // 6: mysql.MysqlOperation.Clone:input_type -> mysql.CloneRequest
	4,  // 7: mysql.MysqlOperation.PhysicalBackup:input_type -> mysql.PhysicalBackupRequest
	3,  // 8: mysql.MysqlOperation.LogicalBackup:input_type -> mysql.LogicalBackupRequest
	5,  // 9: mysql.MysqlOperation.Restore:input_type -> mysql.RestoreRequest
	6,  // 10: mysql.MysqlOperation.GtidPurge:input_type -> mysql.GtidPurgeRequest
	7,  // 11: mysql.MysqlOperation.SetVariable:input_type -> mysql.SetVariableRequest
	9,  // 12: mysql.MysqlOperation.Clone:output_type -> common.Empty
	9,  // 13: mysql.MysqlOperation.PhysicalBackup:output_type -> common.Empty
	9,  // 14: mysql.MysqlOperation.LogicalBackup:output_type -> common.Empty
	9,  // 15: mysql.MysqlOperation.Restore:output_type -> common.Empty
	9,  // 16: mysql.MysqlOperation.GtidPurge:output_type -> common.Empty
	9,  // 17: mysql.MysqlOperation.SetVariable:output_type -> common.Empty
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_pkg_agent_app_mysql_pb_mysql_proto_init() }
func file_pkg_agent_app_mysql_pb_mysql_proto_init() {
	if File_pkg_agent_app_mysql_pb_mysql_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_agent_app_mysql_pb_mysql_proto_rawDesc), len(file_pkg_agent_app_mysql_pb_mysql_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_agent_app_mysql_pb_mysql_proto_goTypes,
		DependencyIndexes: file_pkg_agent_app_mysql_pb_mysql_proto_depIdxs,
		EnumInfos:         file_pkg_agent_app_mysql_pb_mysql_proto_enumTypes,
		MessageInfos:      file_pkg_agent_app_mysql_pb_mysql_proto_msgTypes,
	}.Build()
	File_pkg_agent_app_mysql_pb_mysql_proto = out.File
	file_pkg_agent_app_mysql_pb_mysql_proto_goTypes = nil
	file_pkg_agent_app_mysql_pb_mysql_proto_depIdxs = nil
}
