{{- if .Values.rbac.create -}}
apiVersion: {{ include "common.capabilities.rbac.apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  name: {{ template "unit-operator.fullname" . }}-metrics-reader
  labels: {{- include "common.labels.standard" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "unit-operator.fullname" . }}-metrics-reader
subjects:
  - kind: ServiceAccount
    name: {{ template "unit-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}