apiVersion: v1
kind: Service
metadata:
  name: unit-operator-webhook-service
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ .Values.service.ipFamilyPolicy }}
  {{- end }}
  {{- if .Values.service.ipFamilies }}
  ipFamilies: {{ .Values.service.ipFamilies | toYaml | nindent 2 }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: webhook-server
      name: webhook-server
      protocol: TCP
  selector:
    {{- include "common.labels.matchLabels" . | nindent 4 }}
