apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: unit-operator
    app.kubernetes.io/instance: unit-operator
    app.kubernetes.io/component: controller
    app.kubernetes.io/version: v1.1.0
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    app.kubernetes.io/name: unit-operator
    app.kubernetes.io/instance: unit-operator
    app.kubernetes.io/component: controller
    app.kubernetes.io/version: v1.1.0
    app: unit-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: unit-operator
      app.kubernetes.io/instance: unit-operator
      app.kubernetes.io/component: controller
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: unit-operator
        app.kubernetes.io/instance: unit-operator
        app.kubernetes.io/component: controller
        app.kubernetes.io/version: v1.1.0
    spec:
      securityContext:
        runAsNonRoot: true
      serviceAccountName: controller-manager
      containers:
      - name: manager
        image: quay.io/upmio/unit-operator:v1.1.0
        imagePullPolicy: IfNotPresent
        args:
        - "--leader-elect"
        - "--health-probe-bind-address=:8081"
        - "--metrics-bind-address=127.0.0.1:8080"
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 2
            memory: 4G
          requests:
            cpu: 1
            memory: 2G