---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-upm-syntropycloud-io-v1alpha2-project
  failurePolicy: Fail
  name: mproject.kb.io
  rules:
  - apiGroups:
    - upm.syntropycloud.io
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - projects
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-upm-syntropycloud-io-v1alpha2-unit
  failurePolicy: Fail
  name: munit.kb.io
  rules:
  - apiGroups:
    - upm.syntropycloud.io
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - units
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-upm-syntropycloud-io-v1alpha2-unitset
  failurePolicy: Fail
  name: munitset.kb.io
  rules:
  - apiGroups:
    - upm.syntropycloud.io
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - unitsets
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-upm-syntropycloud-io-v1alpha2-project
  failurePolicy: Fail
  name: vproject.kb.io
  rules:
  - apiGroups:
    - upm.syntropycloud.io
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - projects
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-upm-syntropycloud-io-v1alpha2-unit
  failurePolicy: Fail
  name: vunit.kb.io
  rules:
  - apiGroups:
    - upm.syntropycloud.io
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - units
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-upm-syntropycloud-io-v1alpha2-unitset
  failurePolicy: Fail
  name: vunitset.kb.io
  rules:
  - apiGroups:
    - upm.syntropycloud.io
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - unitsets
  sideEffects: None
