// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.0
// source: pkg/agent/app/service/pb/service.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessState int32

const (
	ProcessState_StateStopped  ProcessState = 0
	ProcessState_StateStarting ProcessState = 1
	ProcessState_StateRunning  ProcessState = 2
	ProcessState_StateBackoff  ProcessState = 3
	ProcessState_StateStopping ProcessState = 4
	ProcessState_StateExited   ProcessState = 5
	ProcessState_StateFatal    ProcessState = 6
	ProcessState_StateUnknown  ProcessState = 7
)

// Enum value maps for ProcessState.
var (
	ProcessState_name = map[int32]string{
		0: "StateStopped",
		1: "StateStarting",
		2: "StateRunning",
		3: "StateBackoff",
		4: "StateStopping",
		5: "StateExited",
		6: "StateFatal",
		7: "StateUnknown",
	}
	ProcessState_value = map[string]int32{
		"StateStopped":  0,
		"StateStarting": 1,
		"StateRunning":  2,
		"StateBackoff":  3,
		"StateStopping": 4,
		"StateExited":   5,
		"StateFatal":    6,
		"StateUnknown":  7,
	}
)

func (x ProcessState) Enum() *ProcessState {
	p := new(ProcessState)
	*p = x
	return p
}

func (x ProcessState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProcessState) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_agent_app_service_pb_service_proto_enumTypes[0].Descriptor()
}

func (ProcessState) Type() protoreflect.EnumType {
	return &file_pkg_agent_app_service_pb_service_proto_enumTypes[0]
}

func (x ProcessState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProcessState.Descriptor instead.
func (ProcessState) EnumDescriptor() ([]byte, []int) {
	return file_pkg_agent_app_service_pb_service_proto_rawDescGZIP(), []int{0}
}

type ServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceRequest) Reset() {
	*x = ServiceRequest{}
	mi := &file_pkg_agent_app_service_pb_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceRequest) ProtoMessage() {}

func (x *ServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_app_service_pb_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceRequest.ProtoReflect.Descriptor instead.
func (*ServiceRequest) Descriptor() ([]byte, []int) {
	return file_pkg_agent_app_service_pb_service_proto_rawDescGZIP(), []int{0}
}

type ServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceResponse) Reset() {
	*x = ServiceResponse{}
	mi := &file_pkg_agent_app_service_pb_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceResponse) ProtoMessage() {}

func (x *ServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_app_service_pb_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceResponse.ProtoReflect.Descriptor instead.
func (*ServiceResponse) Descriptor() ([]byte, []int) {
	return file_pkg_agent_app_service_pb_service_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ServiceStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceStatus ProcessState           `protobuf:"varint,1,opt,name=ServiceStatus,proto3,enum=service.ProcessState" json:"ServiceStatus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceStatusResponse) Reset() {
	*x = ServiceStatusResponse{}
	mi := &file_pkg_agent_app_service_pb_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceStatusResponse) ProtoMessage() {}

func (x *ServiceStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_app_service_pb_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceStatusResponse.ProtoReflect.Descriptor instead.
func (*ServiceStatusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_agent_app_service_pb_service_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceStatusResponse) GetServiceStatus() ProcessState {
	if x != nil {
		return x.ServiceStatus
	}
	return ProcessState_StateStopped
}

var File_pkg_agent_app_service_pb_service_proto protoreflect.FileDescriptor

const file_pkg_agent_app_service_pb_service_proto_rawDesc = "" +
	"\n" +
	"&pkg/agent/app/service/pb/service.proto\x12\aservice\"\x10\n" +
	"\x0eServiceRequest\"+\n" +
	"\x0fServiceResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"T\n" +
	"\x15ServiceStatusResponse\x12;\n" +
	"\rServiceStatus\x18\x01 \x01(\x0e2\x15.service.ProcessStateR\rServiceStatus*\x9d\x01\n" +
	"\fProcessState\x12\x10\n" +
	"\fStateStopped\x10\x00\x12\x11\n" +
	"\rStateStarting\x10\x01\x12\x10\n" +
	"\fStateRunning\x10\x02\x12\x10\n" +
	"\fStateBackoff\x10\x03\x12\x11\n" +
	"\rStateStopping\x10\x04\x12\x0f\n" +
	"\vStateExited\x10\x05\x12\x0e\n" +
	"\n" +
	"StateFatal\x10\x06\x12\x10\n" +
	"\fStateUnknown\x10\a2\xbc\x03\n" +
	"\x10ServiceLifecycle\x12A\n" +
	"\fStartService\x12\x17.service.ServiceRequest\x1a\x18.service.ServiceResponse\x12@\n" +
	"\vStopService\x12\x17.service.ServiceRequest\x1a\x18.service.ServiceResponse\x12C\n" +
	"\x0eRestartService\x12\x17.service.ServiceRequest\x1a\x18.service.ServiceResponse\x12K\n" +
	"\x10GetServiceStatus\x12\x17.service.ServiceRequest\x1a\x1e.service.ServiceStatusResponse\x12G\n" +
	"\x12CheckServiceStatus\x12\x17.service.ServiceRequest\x1a\x18.service.ServiceResponse\x12H\n" +
	"\x13CheckServiceStopped\x12\x17.service.ServiceRequest\x1a\x18.service.ServiceResponseB6Z4github.com/upmio/unit-operator/pkg/agent/app/serviceb\x06proto3"

var (
	file_pkg_agent_app_service_pb_service_proto_rawDescOnce sync.Once
	file_pkg_agent_app_service_pb_service_proto_rawDescData []byte
)

func file_pkg_agent_app_service_pb_service_proto_rawDescGZIP() []byte {
	file_pkg_agent_app_service_pb_service_proto_rawDescOnce.Do(func() {
		file_pkg_agent_app_service_pb_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_agent_app_service_pb_service_proto_rawDesc), len(file_pkg_agent_app_service_pb_service_proto_rawDesc)))
	})
	return file_pkg_agent_app_service_pb_service_proto_rawDescData
}

var file_pkg_agent_app_service_pb_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_agent_app_service_pb_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_agent_app_service_pb_service_proto_goTypes = []any{
	(ProcessState)(0),             // 0: service.ProcessState
	(*ServiceRequest)(nil),        // 1: service.ServiceRequest
	(*ServiceResponse)(nil),       // 2: service.ServiceResponse
	(*ServiceStatusResponse)(nil), // 3: service.ServiceStatusResponse
}
var file_pkg_agent_app_service_pb_service_proto_depIdxs = []int32{
	0, // 0: service.ServiceStatusResponse.ServiceStatus:type_name -> service.ProcessState
	1, // 1: service.ServiceLifecycle.StartService:input_type -> service.ServiceRequest
	1, // 2: service.ServiceLifecycle.StopService:input_type -> service.ServiceRequest
	1, // 3: service.ServiceLifecycle.RestartService:input_type -> service.ServiceRequest
	1, // 4: service.ServiceLifecycle.GetServiceStatus:input_type -> service.ServiceRequest
	1, // 5: service.ServiceLifecycle.CheckServiceStatus:input_type -> service.ServiceRequest
	1, // 6: service.ServiceLifecycle.CheckServiceStopped:input_type -> service.ServiceRequest
	2, // 7: service.ServiceLifecycle.StartService:output_type -> service.ServiceResponse
	2, // 8: service.ServiceLifecycle.StopService:output_type -> service.ServiceResponse
	2, // 9: service.ServiceLifecycle.RestartService:output_type -> service.ServiceResponse
	3, // 10: service.ServiceLifecycle.GetServiceStatus:output_type -> service.ServiceStatusResponse
	2, // 11: service.ServiceLifecycle.CheckServiceStatus:output_type -> service.ServiceResponse
	2, // 12: service.ServiceLifecycle.CheckServiceStopped:output_type -> service.ServiceResponse
	7, // [7:13] is the sub-list for method output_type
	1, // [1:7] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_agent_app_service_pb_service_proto_init() }
func file_pkg_agent_app_service_pb_service_proto_init() {
	if File_pkg_agent_app_service_pb_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_agent_app_service_pb_service_proto_rawDesc), len(file_pkg_agent_app_service_pb_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_agent_app_service_pb_service_proto_goTypes,
		DependencyIndexes: file_pkg_agent_app_service_pb_service_proto_depIdxs,
		EnumInfos:         file_pkg_agent_app_service_pb_service_proto_enumTypes,
		MessageInfos:      file_pkg_agent_app_service_pb_service_proto_msgTypes,
	}.Build()
	File_pkg_agent_app_service_pb_service_proto = out.File
	file_pkg_agent_app_service_pb_service_proto_goTypes = nil
	file_pkg_agent_app_service_pb_service_proto_depIdxs = nil
}
