apiVersion: upm.syntropycloud.io/v1alpha1
kind: GrpcCall
metadata:
  name: clickhouse-set-variable
spec:
  targetUnit: clickhouse-sample-0
  type: clickhouse
  action: set-variable
  ttlSecondsAfterFinished: 3600
  parameters:
    username: admin
    objectStorage:
      endpoint: s3.example.com
      bucket: upm-backups
      accessKey: minio-access-key
      secretKey: minio-secret-key
      ssl: true
      type: Minio
    key: max_threads
    value: "8"
