# permissions for end users to view grpccalls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: unit-operator
    app.kubernetes.io/managed-by: kustomize
  name: grpccall-viewer-role
rules:
- apiGroups:
  - upm.syntropycloud.io
  resources:
  - grpccalls
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - upm.syntropycloud.io
  resources:
  - grpccalls/status
  verbs:
  - get
