# permissions for end users to edit unitsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: unitset-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: upm
    app.kubernetes.io/part-of: upm
    app.kubernetes.io/managed-by: kustomize
  name: unitset-editor-role
rules:
- apiGroups:
  - upm.syntropycloud.io
  resources:
  - unitsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - upm.syntropycloud.io
  resources:
  - unitsets/status
  verbs:
  - get