// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.0
// source: pkg/agent/app/common/pb/common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ObjectStorageType int32

const (
	ObjectStorageType_Minio ObjectStorageType = 0
	ObjectStorageType_Aws   ObjectStorageType = 1 // preserve
)

// Enum value maps for ObjectStorageType.
var (
	ObjectStorageType_name = map[int32]string{
		0: "Minio",
		1: "Aws",
	}
	ObjectStorageType_value = map[string]int32{
		"Minio": 0,
		"Aws":   1,
	}
)

func (x ObjectStorageType) Enum() *ObjectStorageType {
	p := new(ObjectStorageType)
	*p = x
	return p
}

func (x ObjectStorageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ObjectStorageType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_agent_app_common_pb_common_proto_enumTypes[0].Descriptor()
}

func (ObjectStorageType) Type() protoreflect.EnumType {
	return &file_pkg_agent_app_common_pb_common_proto_enumTypes[0]
}

func (x ObjectStorageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ObjectStorageType.Descriptor instead.
func (ObjectStorageType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_agent_app_common_pb_common_proto_rawDescGZIP(), []int{0}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_pkg_agent_app_common_pb_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_app_common_pb_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_pkg_agent_app_common_pb_common_proto_rawDescGZIP(), []int{0}
}

type ObjectStorage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Bucket        string                 `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	AccessKey     string                 `protobuf:"bytes,3,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	SecretKey     string                 `protobuf:"bytes,4,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	Ssl           bool                   `protobuf:"varint,5,opt,name=ssl,proto3" json:"ssl,omitempty"`
	Type          ObjectStorageType      `protobuf:"varint,6,opt,name=type,proto3,enum=common.ObjectStorageType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectStorage) Reset() {
	*x = ObjectStorage{}
	mi := &file_pkg_agent_app_common_pb_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectStorage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectStorage) ProtoMessage() {}

func (x *ObjectStorage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_app_common_pb_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectStorage.ProtoReflect.Descriptor instead.
func (*ObjectStorage) Descriptor() ([]byte, []int) {
	return file_pkg_agent_app_common_pb_common_proto_rawDescGZIP(), []int{1}
}

func (x *ObjectStorage) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *ObjectStorage) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *ObjectStorage) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *ObjectStorage) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

func (x *ObjectStorage) GetSsl() bool {
	if x != nil {
		return x.Ssl
	}
	return false
}

func (x *ObjectStorage) GetType() ObjectStorageType {
	if x != nil {
		return x.Type
	}
	return ObjectStorageType_Minio
}

var File_pkg_agent_app_common_pb_common_proto protoreflect.FileDescriptor

const file_pkg_agent_app_common_pb_common_proto_rawDesc = "" +
	"\n" +
	"$pkg/agent/app/common/pb/common.proto\x12\x06common\"\a\n" +
	"\x05Empty\"\xc2\x01\n" +
	"\rObjectStorage\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12\x16\n" +
	"\x06bucket\x18\x02 \x01(\tR\x06bucket\x12\x1d\n" +
	"\n" +
	"access_key\x18\x03 \x01(\tR\taccessKey\x12\x1d\n" +
	"\n" +
	"secret_key\x18\x04 \x01(\tR\tsecretKey\x12\x10\n" +
	"\x03ssl\x18\x05 \x01(\bR\x03ssl\x12-\n" +
	"\x04type\x18\x06 \x01(\x0e2\x19.common.ObjectStorageTypeR\x04type*'\n" +
	"\x11ObjectStorageType\x12\t\n" +
	"\x05Minio\x10\x00\x12\a\n" +
	"\x03Aws\x10\x01B5Z3github.com/upmio/unit-operator/pkg/agent/app/commonb\x06proto3"

var (
	file_pkg_agent_app_common_pb_common_proto_rawDescOnce sync.Once
	file_pkg_agent_app_common_pb_common_proto_rawDescData []byte
)

func file_pkg_agent_app_common_pb_common_proto_rawDescGZIP() []byte {
	file_pkg_agent_app_common_pb_common_proto_rawDescOnce.Do(func() {
		file_pkg_agent_app_common_pb_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_agent_app_common_pb_common_proto_rawDesc), len(file_pkg_agent_app_common_pb_common_proto_rawDesc)))
	})
	return file_pkg_agent_app_common_pb_common_proto_rawDescData
}

var file_pkg_agent_app_common_pb_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_agent_app_common_pb_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_agent_app_common_pb_common_proto_goTypes = []any{
	(ObjectStorageType)(0), // 0: common.ObjectStorageType
	(*Empty)(nil),          // 1: common.Empty
	(*ObjectStorage)(nil),  // 2: common.ObjectStorage
}
var file_pkg_agent_app_common_pb_common_proto_depIdxs = []int32{
	0, // 0: common.ObjectStorage.type:type_name -> common.ObjectStorageType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_agent_app_common_pb_common_proto_init() }
func file_pkg_agent_app_common_pb_common_proto_init() {
	if File_pkg_agent_app_common_pb_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_agent_app_common_pb_common_proto_rawDesc), len(file_pkg_agent_app_common_pb_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_agent_app_common_pb_common_proto_goTypes,
		DependencyIndexes: file_pkg_agent_app_common_pb_common_proto_depIdxs,
		EnumInfos:         file_pkg_agent_app_common_pb_common_proto_enumTypes,
		MessageInfos:      file_pkg_agent_app_common_pb_common_proto_msgTypes,
	}.Build()
	File_pkg_agent_app_common_pb_common_proto = out.File
	file_pkg_agent_app_common_pb_common_proto_goTypes = nil
	file_pkg_agent_app_common_pb_common_proto_depIdxs = nil
}
