// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.0
// source: pkg/agent/app/redis/pb/redis.proto

package redis

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetVariableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Password      string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetVariableRequest) Reset() {
	*x = SetVariableRequest{}
	mi := &file_pkg_agent_app_redis_pb_redis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetVariableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetVariableRequest) ProtoMessage() {}

func (x *SetVariableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_app_redis_pb_redis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetVariableRequest.ProtoReflect.Descriptor instead.
func (*SetVariableRequest) Descriptor() ([]byte, []int) {
	return file_pkg_agent_app_redis_pb_redis_proto_rawDescGZIP(), []int{0}
}

func (x *SetVariableRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetVariableRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SetVariableRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_pkg_agent_app_redis_pb_redis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_app_redis_pb_redis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_pkg_agent_app_redis_pb_redis_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pkg_agent_app_redis_pb_redis_proto protoreflect.FileDescriptor

const file_pkg_agent_app_redis_pb_redis_proto_rawDesc = "" +
	"\n" +
	"\"pkg/agent/app/redis/pb/redis.proto\x12\x05redis\"X\n" +
	"\x12SetVariableRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\"$\n" +
	"\bResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2K\n" +
	"\x0eRedisOperation\x129\n" +
	"\vSetVariable\x12\x19.redis.SetVariableRequest\x1a\x0f.redis.ResponseB4Z2github.com/upmio/unit-operator/pkg/agent/app/redisb\x06proto3"

var (
	file_pkg_agent_app_redis_pb_redis_proto_rawDescOnce sync.Once
	file_pkg_agent_app_redis_pb_redis_proto_rawDescData []byte
)

func file_pkg_agent_app_redis_pb_redis_proto_rawDescGZIP() []byte {
	file_pkg_agent_app_redis_pb_redis_proto_rawDescOnce.Do(func() {
		file_pkg_agent_app_redis_pb_redis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_agent_app_redis_pb_redis_proto_rawDesc), len(file_pkg_agent_app_redis_pb_redis_proto_rawDesc)))
	})
	return file_pkg_agent_app_redis_pb_redis_proto_rawDescData
}

var file_pkg_agent_app_redis_pb_redis_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_agent_app_redis_pb_redis_proto_goTypes = []any{
	(*SetVariableRequest)(nil), // 0: redis.SetVariableRequest
	(*Response)(nil),           // 1: redis.Response
}
var file_pkg_agent_app_redis_pb_redis_proto_depIdxs = []int32{
	0, // 0: redis.RedisOperation.SetVariable:input_type -> redis.SetVariableRequest
	1, // 1: redis.RedisOperation.SetVariable:output_type -> redis.Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_agent_app_redis_pb_redis_proto_init() }
func file_pkg_agent_app_redis_pb_redis_proto_init() {
	if File_pkg_agent_app_redis_pb_redis_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_agent_app_redis_pb_redis_proto_rawDesc), len(file_pkg_agent_app_redis_pb_redis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_agent_app_redis_pb_redis_proto_goTypes,
		DependencyIndexes: file_pkg_agent_app_redis_pb_redis_proto_depIdxs,
		MessageInfos:      file_pkg_agent_app_redis_pb_redis_proto_msgTypes,
	}.Build()
	File_pkg_agent_app_redis_pb_redis_proto = out.File
	file_pkg_agent_app_redis_pb_redis_proto_goTypes = nil
	file_pkg_agent_app_redis_pb_redis_proto_depIdxs = nil
}
