// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.36.0
// source: pkg/agent/app/redis/pb/redis.proto

package redis

import (
	context "context"
	common "github.com/upmio/unit-operator/pkg/agent/app/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RedisOperation_SetVariable_FullMethodName = "/redis.RedisOperation/SetVariable"
	RedisOperation_Backup_FullMethodName      = "/redis.RedisOperation/Backup"
	RedisOperation_Restore_FullMethodName     = "/redis.RedisOperation/Restore"
)

// RedisOperationClient is the client API for RedisOperation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RedisOperationClient interface {
	SetVariable(ctx context.Context, in *SetVariableRequest, opts ...grpc.CallOption) (*common.Empty, error)
	Backup(ctx context.Context, in *BackupRequest, opts ...grpc.CallOption) (*common.Empty, error)
	Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*common.Empty, error)
}

type redisOperationClient struct {
	cc grpc.ClientConnInterface
}

func NewRedisOperationClient(cc grpc.ClientConnInterface) RedisOperationClient {
	return &redisOperationClient{cc}
}

func (c *redisOperationClient) SetVariable(ctx context.Context, in *SetVariableRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, RedisOperation_SetVariable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisOperationClient) Backup(ctx context.Context, in *BackupRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, RedisOperation_Backup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisOperationClient) Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, RedisOperation_Restore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RedisOperationServer is the server API for RedisOperation service.
// All implementations must embed UnimplementedRedisOperationServer
// for forward compatibility.
type RedisOperationServer interface {
	SetVariable(context.Context, *SetVariableRequest) (*common.Empty, error)
	Backup(context.Context, *BackupRequest) (*common.Empty, error)
	Restore(context.Context, *RestoreRequest) (*common.Empty, error)
	mustEmbedUnimplementedRedisOperationServer()
}

// UnimplementedRedisOperationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRedisOperationServer struct{}

func (UnimplementedRedisOperationServer) SetVariable(context.Context, *SetVariableRequest) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetVariable not implemented")
}
func (UnimplementedRedisOperationServer) Backup(context.Context, *BackupRequest) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Backup not implemented")
}
func (UnimplementedRedisOperationServer) Restore(context.Context, *RestoreRequest) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Restore not implemented")
}
func (UnimplementedRedisOperationServer) mustEmbedUnimplementedRedisOperationServer() {}
func (UnimplementedRedisOperationServer) testEmbeddedByValue()                        {}

// UnsafeRedisOperationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RedisOperationServer will
// result in compilation errors.
type UnsafeRedisOperationServer interface {
	mustEmbedUnimplementedRedisOperationServer()
}

func RegisterRedisOperationServer(s grpc.ServiceRegistrar, srv RedisOperationServer) {
	// If the following call pancis, it indicates UnimplementedRedisOperationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RedisOperation_ServiceDesc, srv)
}

func _RedisOperation_SetVariable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetVariableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisOperationServer).SetVariable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisOperation_SetVariable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisOperationServer).SetVariable(ctx, req.(*SetVariableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisOperation_Backup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisOperationServer).Backup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisOperation_Backup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisOperationServer).Backup(ctx, req.(*BackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisOperation_Restore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisOperationServer).Restore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisOperation_Restore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisOperationServer).Restore(ctx, req.(*RestoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RedisOperation_ServiceDesc is the grpc.ServiceDesc for RedisOperation service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RedisOperation_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "redis.RedisOperation",
	HandlerType: (*RedisOperationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetVariable",
			Handler:    _RedisOperation_SetVariable_Handler,
		},
		{
			MethodName: "Backup",
			Handler:    _RedisOperation_Backup_Handler,
		},
		{
			MethodName: "Restore",
			Handler:    _RedisOperation_Restore_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/agent/app/redis/pb/redis.proto",
}
