sequenceDiagram
    participant User
    participant API Server
    participant PVC Controller
    participant Scheduler
    participant Kubelet
    participant Unit Agent
    participant Unit Controller
    

    User->>API Server: Create Unit
    API Server-->>User: Confirm creation

    Unit Controller->>API Server: Listen to Unit changes
    API Server-->>Unit Controller: Notify new Unit creation

    Unit Controller->>API Server: Create the pvc
    API Server->>PVC Controller: Notify new pvc creation

    Unit Controller->>Unit Controller: Update unit status
    
    Unit Controller->>API Server: Create Pod

    Scheduler->>API Server: Listen for unscheduled Pods
    API Server-->>Scheduler: Notify new Pod creation

    Scheduler->>API Server: Assign nodes to Pods

    Kubelet->>API Server: Listen to the Pod assigned to this node
    API Server-->>Kubelet: Notify of new Pod assignments

    Kubelet->>Kubelet: Create container
    Kubelet->>API Server: Update Pod Status

    Unit Controller->>API Server: Listen to pod status
    
    Unit Controller->>Unit Controller: Update unit status
    
    Unit Controller->>Unit Agent: Load unit config

    Unit Controller->>Unit Agent: Start the process

    Unit Controller->>Unit Controller: Update unit status