---
# Generic gRPC call sample for health check
apiVersion: upm.syntropycloud.io/v1alpha1
kind: GrpcCall
metadata:
  labels:
    app.kubernetes.io/name: unit-operator
    app.kubernetes.io/managed-by: kustomize
  name: grpccall-health-check
spec:
  targetUnit: example-unitset-0
  type: generic
  action: health-check
  parameters:
    endpoint: "localhost:50051"
    service: "health.Health"
    method: "Check"
    timeout: "30s"

---
# Generic gRPC call sample for service discovery
apiVersion: upm.syntropycloud.io/v1alpha1
kind: GrpcCall
metadata:
  labels:
    app.kubernetes.io/name: unit-operator
    app.kubernetes.io/managed-by: kustomize
  name: grpccall-service-discovery
spec:
  targetUnit: example-unitset-0
  type: generic
  action: service-discovery
  parameters:
    endpoint: "localhost:50051"
    service: "discovery.Discovery"
    method: "Register"
    timeout: "30s"

---
# Generic gRPC call sample for configuration sync
apiVersion: upm.syntropycloud.io/v1alpha1
kind: GrpcCall
metadata:
  labels:
    app.kubernetes.io/name: unit-operator
    app.kubernetes.io/managed-by: kustomize
  name: grpccall-config-sync
spec:
  targetUnit: example-unitset-0
  type: generic
  action: config-sync
  parameters:
    endpoint: "localhost:50051"
    service: "config.Config"
    method: "Sync"
    timeout: "60s"

---
# Legacy database-specific examples (commented out)
# These examples are preserved for reference but should be adapted for generic use
# ---
# #mysql logical backup sample
# apiVersion: upm.syntropycloud.io/v1alpha1
# kind: GrpcCall
# metadata:
#   labels:
#     app.kubernetes.io/name: unit-operator
#     app.kubernetes.io/managed-by: kustomize
#   name: grpccall-sample
# spec:
#   targetUnit: gegx7qnj-mysql-rqu-0
#   type: mysql
#   action: logical-backup
#   parameters:
#     backupFile: mysql-backup-20250516
#     confFile: "/DATA_MOUNT/conf/mysqld.cnf"
#     socketFile: "/DATA_MOUNT/mysqld.sock"
#     username: root
#     password: password
#     database: test
#     table: table1
#     logicalBackupMode: 0
#     s3Storage:
#       endpoint: s3://192.168.1.1
#       bucket: mysql-backup
#       accessKey: accesskey
#       secretKey: secretkey