apiVersion: tesseract-cube.bsgchina.com/v1alpha1
kind: UnitSet
metadata:
  finalizers:
    - upm.io/unit-delete
    - upm.io/configmap-delete
  labels:
    app.kubernetes.io/name: unitset
    app.kubernetes.io/instance: unitset-sample
    app.kubernetes.io/part-of: tesseract-cube
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: tesseract-cube
    upm.api/service-group.name: tesseract-cube-unitset
    upm.api/service-group.type: mysql-sg
    upm.api/service.type: mysql
    upm.io/owner: upm
  name: tesseract-cube-unitset
  namespace: tesseract-cube-namespace
spec:
  architecture:
    mode: rpl_async
    units: 1
  image:
    arch: amd64
    build: 1
    major: 8
    minor: 0
    patch: 34
    type: mysql
  serviceInfo:
    serviceType: "ClusterIP"
  sharedConfigName: tesseract-cube-configmap
  template:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: upm.api/software.mysql
                  operator: In
                  values:
                    - "true"
                - key: upm.api/node-group
                  operator: In
                  values:
                    - tesseract-cube-unitset
    env:
      - name: tesseract-cube-UNITSET
        value: tesseract-cube-UNITSET
    resource:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 1Gi
    serviceAccount: tesseract-cube-sa
    serviceInfo:
      serviceType: "NodePort"
    unbindNode: true
    volumeMounts:
      - mountPath: /DATA_MOUNT
        name: data
    volumes:
      - name: secret
        secret:
          secretName: tesseract-cube-secret
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: tesseract-cube-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: tesseract-cube-ssd
        volumeMode: Filesystem