apiVersion: tesseract-cube.bsgchina.com/v1alpha1
kind: Unit
metadata:
  annotations:
    shared_config_name: tesseract-cube-configmap
  finalizers:
    - upm.io/pod-delete
    - upm.io/configmap-delete
    - upm.io/pvc-delete
    - upm.io/service-delete
  labels:
    app.kubernetes.io/name: unit
    app.kubernetes.io/instance: unit-sample
    app.kubernetes.io/part-of: tesseract-cube
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: tesseract-cube
    upm.io/owner: tesseract-cube
  name: tesseract-cube-unit
  namespace: tesseract-cube
spec:
  mainContainerName: mysql
  mainImageVersion: 8.0.34.1-amd64
  serviceInfo:
    serviceType: "NodePort"
  startup: true
  template:
    spec:
      containers:
        - env:
            - name: ADM_USER
              value: root
          image: quay.io/upmio/mysql@sha256:f32132d330e68c500b9cd8dc7ad6e5952f87ae324ea39ef12cf111b431b1d400
          livenessProbe:
            exec:
              command:
                - timeout
                - "3"
                - bash
                - -c
                - </dev/tcp/localhost/9001
            failureThreshold: 3
            initialDelaySeconds: 12
            periodSeconds: 12
            timeoutSeconds: 4
          name: mysql
          ports:
            - containerPort: 3306
              name: mysql
          readinessProbe:
            exec:
              command:
                - bash
                - -c
                - mysqladmin --defaults-file=${CONF_DIR}/.monitor.cnf status
            failureThreshold: 3
            initialDelaySeconds: 12
            periodSeconds: 12
            timeoutSeconds: 4
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 1Gi
          startupProbe:
            exec:
              command:
                - timeout
                - "3"
                - bash
                - -c
                - </dev/tcp/localhost/9001
            failureThreshold: 3
            periodSeconds: 12
            timeoutSeconds: 4
      enableServiceLinks: true
      hostname: tesseract-cube
      initContainers:
        - command:
            - bash
            - -c
            - serverMGR.sh initialize
          env:
            - name: TESSETACTCUBE_UNIT
              value: tesseract-cube-unit
          image: quay.io/upmio/mysql@sha256:f32132d330e68c500b9cd8dc7ad6e5952f87ae324ea39ef12cf111b431b1d400
          name: init-container
      serviceAccountName: tesseract-cube-sa
      subdomain: tesseract-cube-headless-svc
  unBindNode: true
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: tesseract-cube
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: tesseract-cube-ssd
        volumeMode: Filesystem
  volumeMounts:
    - mountPath: /DATA_MOUNT
      name: tesseract-cube
  volumes:
    - name: secret
      secret:
        secretName: tesseract-cube-secret