// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.0
// source: pkg/agent/app/postgresql/pb/postgresql.proto

package postgresql

import (
	common "github.com/upmio/unit-operator/pkg/agent/app/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogicalBackupMode int32

const (
	LogicalBackupMode_Full     LogicalBackupMode = 0
	LogicalBackupMode_Database LogicalBackupMode = 1
	LogicalBackupMode_Table    LogicalBackupMode = 2
)

// Enum value maps for LogicalBackupMode.
var (
	LogicalBackupMode_name = map[int32]string{
		0: "Full",
		1: "Database",
		2: "Table",
	}
	LogicalBackupMode_value = map[string]int32{
		"Full":     0,
		"Database": 1,
		"Table":    2,
	}
)

func (x LogicalBackupMode) Enum() *LogicalBackupMode {
	p := new(LogicalBackupMode)
	*p = x
	return p
}

func (x LogicalBackupMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogicalBackupMode) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_agent_app_postgresql_pb_postgresql_proto_enumTypes[0].Descriptor()
}

func (LogicalBackupMode) Type() protoreflect.EnumType {
	return &file_pkg_agent_app_postgresql_pb_postgresql_proto_enumTypes[0]
}

func (x LogicalBackupMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogicalBackupMode.Descriptor instead.
func (LogicalBackupMode) EnumDescriptor() ([]byte, []int) {
	return file_pkg_agent_app_postgresql_pb_postgresql_proto_rawDescGZIP(), []int{0}
}

type LogicalBackupRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BackupFile        string                 `protobuf:"bytes,1,opt,name=backup_file,json=backupFile,proto3" json:"backup_file,omitempty"`
	Username          string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Database          string                 `protobuf:"bytes,3,opt,name=database,proto3" json:"database,omitempty"`
	Table             string                 `protobuf:"bytes,4,opt,name=table,proto3" json:"table,omitempty"`
	LogicalBackupMode LogicalBackupMode      `protobuf:"varint,5,opt,name=logical_backup_mode,json=logicalBackupMode,proto3,enum=postgresql.LogicalBackupMode" json:"logical_backup_mode,omitempty"`
	ObjectStorage     *common.ObjectStorage  `protobuf:"bytes,6,opt,name=object_storage,json=objectStorage,proto3" json:"object_storage,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LogicalBackupRequest) Reset() {
	*x = LogicalBackupRequest{}
	mi := &file_pkg_agent_app_postgresql_pb_postgresql_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogicalBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicalBackupRequest) ProtoMessage() {}

func (x *LogicalBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_app_postgresql_pb_postgresql_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicalBackupRequest.ProtoReflect.Descriptor instead.
func (*LogicalBackupRequest) Descriptor() ([]byte, []int) {
	return file_pkg_agent_app_postgresql_pb_postgresql_proto_rawDescGZIP(), []int{0}
}

func (x *LogicalBackupRequest) GetBackupFile() string {
	if x != nil {
		return x.BackupFile
	}
	return ""
}

func (x *LogicalBackupRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LogicalBackupRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *LogicalBackupRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *LogicalBackupRequest) GetLogicalBackupMode() LogicalBackupMode {
	if x != nil {
		return x.LogicalBackupMode
	}
	return LogicalBackupMode_Full
}

func (x *LogicalBackupRequest) GetObjectStorage() *common.ObjectStorage {
	if x != nil {
		return x.ObjectStorage
	}
	return nil
}

type PhysicalBackupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BackupFile    string                 `protobuf:"bytes,1,opt,name=backup_file,json=backupFile,proto3" json:"backup_file,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	ObjectStorage *common.ObjectStorage  `protobuf:"bytes,3,opt,name=object_storage,json=objectStorage,proto3" json:"object_storage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhysicalBackupRequest) Reset() {
	*x = PhysicalBackupRequest{}
	mi := &file_pkg_agent_app_postgresql_pb_postgresql_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhysicalBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhysicalBackupRequest) ProtoMessage() {}

func (x *PhysicalBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_app_postgresql_pb_postgresql_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhysicalBackupRequest.ProtoReflect.Descriptor instead.
func (*PhysicalBackupRequest) Descriptor() ([]byte, []int) {
	return file_pkg_agent_app_postgresql_pb_postgresql_proto_rawDescGZIP(), []int{1}
}

func (x *PhysicalBackupRequest) GetBackupFile() string {
	if x != nil {
		return x.BackupFile
	}
	return ""
}

func (x *PhysicalBackupRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PhysicalBackupRequest) GetObjectStorage() *common.ObjectStorage {
	if x != nil {
		return x.ObjectStorage
	}
	return nil
}

type RestoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BackupFile    string                 `protobuf:"bytes,1,opt,name=backup_file,json=backupFile,proto3" json:"backup_file,omitempty"`
	ObjectStorage *common.ObjectStorage  `protobuf:"bytes,2,opt,name=object_storage,json=objectStorage,proto3" json:"object_storage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreRequest) Reset() {
	*x = RestoreRequest{}
	mi := &file_pkg_agent_app_postgresql_pb_postgresql_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreRequest) ProtoMessage() {}

func (x *RestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_app_postgresql_pb_postgresql_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreRequest.ProtoReflect.Descriptor instead.
func (*RestoreRequest) Descriptor() ([]byte, []int) {
	return file_pkg_agent_app_postgresql_pb_postgresql_proto_rawDescGZIP(), []int{2}
}

func (x *RestoreRequest) GetBackupFile() string {
	if x != nil {
		return x.BackupFile
	}
	return ""
}

func (x *RestoreRequest) GetObjectStorage() *common.ObjectStorage {
	if x != nil {
		return x.ObjectStorage
	}
	return nil
}

type SetVariableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetVariableRequest) Reset() {
	*x = SetVariableRequest{}
	mi := &file_pkg_agent_app_postgresql_pb_postgresql_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetVariableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetVariableRequest) ProtoMessage() {}

func (x *SetVariableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_app_postgresql_pb_postgresql_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetVariableRequest.ProtoReflect.Descriptor instead.
func (*SetVariableRequest) Descriptor() ([]byte, []int) {
	return file_pkg_agent_app_postgresql_pb_postgresql_proto_rawDescGZIP(), []int{3}
}

func (x *SetVariableRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetVariableRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SetVariableRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

var File_pkg_agent_app_postgresql_pb_postgresql_proto protoreflect.FileDescriptor

const file_pkg_agent_app_postgresql_pb_postgresql_proto_rawDesc = "" +
	"\n" +
	",pkg/agent/app/postgresql/pb/postgresql.proto\x12\n" +
	"postgresql\x1a$pkg/agent/app/common/pb/common.proto\"\x92\x02\n" +
	"\x14LogicalBackupRequest\x12\x1f\n" +
	"\vbackup_file\x18\x01 \x01(\tR\n" +
	"backupFile\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bdatabase\x18\x03 \x01(\tR\bdatabase\x12\x14\n" +
	"\x05table\x18\x04 \x01(\tR\x05table\x12M\n" +
	"\x13logical_backup_mode\x18\x05 \x01(\x0e2\x1d.postgresql.LogicalBackupModeR\x11logicalBackupMode\x12<\n" +
	"\x0eobject_storage\x18\x06 \x01(\v2\x15.common.ObjectStorageR\robjectStorage\"\x92\x01\n" +
	"\x15PhysicalBackupRequest\x12\x1f\n" +
	"\vbackup_file\x18\x01 \x01(\tR\n" +
	"backupFile\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12<\n" +
	"\x0eobject_storage\x18\x03 \x01(\v2\x15.common.ObjectStorageR\robjectStorage\"o\n" +
	"\x0eRestoreRequest\x12\x1f\n" +
	"\vbackup_file\x18\x01 \x01(\tR\n" +
	"backupFile\x12<\n" +
	"\x0eobject_storage\x18\x02 \x01(\v2\x15.common.ObjectStorageR\robjectStorage\"X\n" +
	"\x12SetVariableRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername*6\n" +
	"\x11LogicalBackupMode\x12\b\n" +
	"\x04Full\x10\x00\x12\f\n" +
	"\bDatabase\x10\x01\x12\t\n" +
	"\x05Table\x10\x022\x8f\x02\n" +
	"\x13PostgresqlOperation\x12B\n" +
	"\x0ePhysicalBackup\x12!.postgresql.PhysicalBackupRequest\x1a\r.common.Empty\x12@\n" +
	"\rLogicalBackup\x12 .postgresql.LogicalBackupRequest\x1a\r.common.Empty\x124\n" +
	"\aRestore\x12\x1a.postgresql.RestoreRequest\x1a\r.common.Empty\x12<\n" +
	"\vSetVariable\x12\x1e.postgresql.SetVariableRequest\x1a\r.common.EmptyB9Z7github.com/upmio/unit-operator/pkg/agent/app/postgresqlb\x06proto3"

var (
	file_pkg_agent_app_postgresql_pb_postgresql_proto_rawDescOnce sync.Once
	file_pkg_agent_app_postgresql_pb_postgresql_proto_rawDescData []byte
)

func file_pkg_agent_app_postgresql_pb_postgresql_proto_rawDescGZIP() []byte {
	file_pkg_agent_app_postgresql_pb_postgresql_proto_rawDescOnce.Do(func() {
		file_pkg_agent_app_postgresql_pb_postgresql_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_agent_app_postgresql_pb_postgresql_proto_rawDesc), len(file_pkg_agent_app_postgresql_pb_postgresql_proto_rawDesc)))
	})
	return file_pkg_agent_app_postgresql_pb_postgresql_proto_rawDescData
}

var file_pkg_agent_app_postgresql_pb_postgresql_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_agent_app_postgresql_pb_postgresql_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_agent_app_postgresql_pb_postgresql_proto_goTypes = []any{
	(LogicalBackupMode)(0),        // 0: postgresql.LogicalBackupMode
	(*LogicalBackupRequest)(nil),  // 1: postgresql.LogicalBackupRequest
	(*PhysicalBackupRequest)(nil), // 2: postgresql.PhysicalBackupRequest
	(*RestoreRequest)(nil),        // 3: postgresql.RestoreRequest
	(*SetVariableRequest)(nil),    // 4: postgresql.SetVariableRequest
	(*common.ObjectStorage)(nil),  // 5: common.ObjectStorage
	(*common.Empty)(nil),          // 6: common.Empty
}
var file_pkg_agent_app_postgresql_pb_postgresql_proto_depIdxs = []int32{
	0, // 0: postgresql.LogicalBackupRequest.logical_backup_mode:type_name -> postgresql.LogicalBackupMode
	5, // 1: postgresql.LogicalBackupRequest.object_storage:type_name -> common.ObjectStorage
	5, // 2: postgresql.PhysicalBackupRequest.object_storage:type_name -> common.ObjectStorage
	5, // 3: postgresql.RestoreRequest.object_storage:type_name -> common.ObjectStorage
	2, // 4: postgresql.PostgresqlOperation.PhysicalBackup:input_type -> postgresql.PhysicalBackupRequest
	1, // 5: postgresql.PostgresqlOperation.LogicalBackup:input_type -> postgresql.LogicalBackupRequest
	3, // 6: postgresql.PostgresqlOperation.Restore:input_type -> postgresql.RestoreRequest
	4, // 7: postgresql.PostgresqlOperation.SetVariable:input_type -> postgresql.SetVariableRequest
	6, // 8: postgresql.PostgresqlOperation.PhysicalBackup:output_type -> common.Empty
	6, // 9: postgresql.PostgresqlOperation.LogicalBackup:output_type -> common.Empty
	6, // 10: postgresql.PostgresqlOperation.Restore:output_type -> common.Empty
	6, // 11: postgresql.PostgresqlOperation.SetVariable:output_type -> common.Empty
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_agent_app_postgresql_pb_postgresql_proto_init() }
func file_pkg_agent_app_postgresql_pb_postgresql_proto_init() {
	if File_pkg_agent_app_postgresql_pb_postgresql_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_agent_app_postgresql_pb_postgresql_proto_rawDesc), len(file_pkg_agent_app_postgresql_pb_postgresql_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_agent_app_postgresql_pb_postgresql_proto_goTypes,
		DependencyIndexes: file_pkg_agent_app_postgresql_pb_postgresql_proto_depIdxs,
		EnumInfos:         file_pkg_agent_app_postgresql_pb_postgresql_proto_enumTypes,
		MessageInfos:      file_pkg_agent_app_postgresql_pb_postgresql_proto_msgTypes,
	}.Build()
	File_pkg_agent_app_postgresql_pb_postgresql_proto = out.File
	file_pkg_agent_app_postgresql_pb_postgresql_proto_goTypes = nil
	file_pkg_agent_app_postgresql_pb_postgresql_proto_depIdxs = nil
}
