// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.0
// source: pkg/agent/app/postgresql/pb/postgresql.proto

package postgresql

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogicalBackupMode int32

const (
	LogicalBackupMode_Full     LogicalBackupMode = 0
	LogicalBackupMode_Database LogicalBackupMode = 1
	LogicalBackupMode_Table    LogicalBackupMode = 2
)

// Enum value maps for LogicalBackupMode.
var (
	LogicalBackupMode_name = map[int32]string{
		0: "Full",
		1: "Database",
		2: "Table",
	}
	LogicalBackupMode_value = map[string]int32{
		"Full":     0,
		"Database": 1,
		"Table":    2,
	}
)

func (x LogicalBackupMode) Enum() *LogicalBackupMode {
	p := new(LogicalBackupMode)
	*p = x
	return p
}

func (x LogicalBackupMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogicalBackupMode) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_agent_app_postgresql_pb_postgresql_proto_enumTypes[0].Descriptor()
}

func (LogicalBackupMode) Type() protoreflect.EnumType {
	return &file_pkg_agent_app_postgresql_pb_postgresql_proto_enumTypes[0]
}

func (x LogicalBackupMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogicalBackupMode.Descriptor instead.
func (LogicalBackupMode) EnumDescriptor() ([]byte, []int) {
	return file_pkg_agent_app_postgresql_pb_postgresql_proto_rawDescGZIP(), []int{0}
}

type S3Storage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Bucket        string                 `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	AccessKey     string                 `protobuf:"bytes,3,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	SecretKey     string                 `protobuf:"bytes,4,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S3Storage) Reset() {
	*x = S3Storage{}
	mi := &file_pkg_agent_app_postgresql_pb_postgresql_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S3Storage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S3Storage) ProtoMessage() {}

func (x *S3Storage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_app_postgresql_pb_postgresql_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S3Storage.ProtoReflect.Descriptor instead.
func (*S3Storage) Descriptor() ([]byte, []int) {
	return file_pkg_agent_app_postgresql_pb_postgresql_proto_rawDescGZIP(), []int{0}
}

func (x *S3Storage) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *S3Storage) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *S3Storage) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *S3Storage) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

type LocalStorage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalStorage) Reset() {
	*x = LocalStorage{}
	mi := &file_pkg_agent_app_postgresql_pb_postgresql_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalStorage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalStorage) ProtoMessage() {}

func (x *LocalStorage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_app_postgresql_pb_postgresql_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalStorage.ProtoReflect.Descriptor instead.
func (*LocalStorage) Descriptor() ([]byte, []int) {
	return file_pkg_agent_app_postgresql_pb_postgresql_proto_rawDescGZIP(), []int{1}
}

func (x *LocalStorage) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type LogicalBackupRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BackupFile        string                 `protobuf:"bytes,1,opt,name=backup_file,json=backupFile,proto3" json:"backup_file,omitempty"`
	Username          string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password          string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Database          string                 `protobuf:"bytes,4,opt,name=database,proto3" json:"database,omitempty"`
	Table             string                 `protobuf:"bytes,5,opt,name=table,proto3" json:"table,omitempty"`
	LogicalBackupMode LogicalBackupMode      `protobuf:"varint,6,opt,name=logicalBackupMode,proto3,enum=postgresql.LogicalBackupMode" json:"logicalBackupMode,omitempty"`
	// Types that are valid to be assigned to StorageType:
	//
	//	*LogicalBackupRequest_S3Storage
	//	*LogicalBackupRequest_LocalStorage
	StorageType   isLogicalBackupRequest_StorageType `protobuf_oneof:"StorageType"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogicalBackupRequest) Reset() {
	*x = LogicalBackupRequest{}
	mi := &file_pkg_agent_app_postgresql_pb_postgresql_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogicalBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicalBackupRequest) ProtoMessage() {}

func (x *LogicalBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_app_postgresql_pb_postgresql_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicalBackupRequest.ProtoReflect.Descriptor instead.
func (*LogicalBackupRequest) Descriptor() ([]byte, []int) {
	return file_pkg_agent_app_postgresql_pb_postgresql_proto_rawDescGZIP(), []int{2}
}

func (x *LogicalBackupRequest) GetBackupFile() string {
	if x != nil {
		return x.BackupFile
	}
	return ""
}

func (x *LogicalBackupRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LogicalBackupRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LogicalBackupRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *LogicalBackupRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *LogicalBackupRequest) GetLogicalBackupMode() LogicalBackupMode {
	if x != nil {
		return x.LogicalBackupMode
	}
	return LogicalBackupMode_Full
}

func (x *LogicalBackupRequest) GetStorageType() isLogicalBackupRequest_StorageType {
	if x != nil {
		return x.StorageType
	}
	return nil
}

func (x *LogicalBackupRequest) GetS3Storage() *S3Storage {
	if x != nil {
		if x, ok := x.StorageType.(*LogicalBackupRequest_S3Storage); ok {
			return x.S3Storage
		}
	}
	return nil
}

func (x *LogicalBackupRequest) GetLocalStorage() *LocalStorage {
	if x != nil {
		if x, ok := x.StorageType.(*LogicalBackupRequest_LocalStorage); ok {
			return x.LocalStorage
		}
	}
	return nil
}

type isLogicalBackupRequest_StorageType interface {
	isLogicalBackupRequest_StorageType()
}

type LogicalBackupRequest_S3Storage struct {
	S3Storage *S3Storage `protobuf:"bytes,7,opt,name=s3_storage,json=s3Storage,proto3,oneof"`
}

type LogicalBackupRequest_LocalStorage struct {
	LocalStorage *LocalStorage `protobuf:"bytes,8,opt,name=local_storage,json=localStorage,proto3,oneof"`
}

func (*LogicalBackupRequest_S3Storage) isLogicalBackupRequest_StorageType() {}

func (*LogicalBackupRequest_LocalStorage) isLogicalBackupRequest_StorageType() {}

type PhysicalBackupRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	BackupFile string                 `protobuf:"bytes,1,opt,name=backup_file,json=backupFile,proto3" json:"backup_file,omitempty"`
	Username   string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password   string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	// Types that are valid to be assigned to StorageType:
	//
	//	*PhysicalBackupRequest_S3Storage
	//	*PhysicalBackupRequest_LocalStorage
	StorageType   isPhysicalBackupRequest_StorageType `protobuf_oneof:"StorageType"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhysicalBackupRequest) Reset() {
	*x = PhysicalBackupRequest{}
	mi := &file_pkg_agent_app_postgresql_pb_postgresql_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhysicalBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhysicalBackupRequest) ProtoMessage() {}

func (x *PhysicalBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_app_postgresql_pb_postgresql_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhysicalBackupRequest.ProtoReflect.Descriptor instead.
func (*PhysicalBackupRequest) Descriptor() ([]byte, []int) {
	return file_pkg_agent_app_postgresql_pb_postgresql_proto_rawDescGZIP(), []int{3}
}

func (x *PhysicalBackupRequest) GetBackupFile() string {
	if x != nil {
		return x.BackupFile
	}
	return ""
}

func (x *PhysicalBackupRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PhysicalBackupRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *PhysicalBackupRequest) GetStorageType() isPhysicalBackupRequest_StorageType {
	if x != nil {
		return x.StorageType
	}
	return nil
}

func (x *PhysicalBackupRequest) GetS3Storage() *S3Storage {
	if x != nil {
		if x, ok := x.StorageType.(*PhysicalBackupRequest_S3Storage); ok {
			return x.S3Storage
		}
	}
	return nil
}

func (x *PhysicalBackupRequest) GetLocalStorage() *LocalStorage {
	if x != nil {
		if x, ok := x.StorageType.(*PhysicalBackupRequest_LocalStorage); ok {
			return x.LocalStorage
		}
	}
	return nil
}

type isPhysicalBackupRequest_StorageType interface {
	isPhysicalBackupRequest_StorageType()
}

type PhysicalBackupRequest_S3Storage struct {
	S3Storage *S3Storage `protobuf:"bytes,4,opt,name=s3_storage,json=s3Storage,proto3,oneof"`
}

type PhysicalBackupRequest_LocalStorage struct {
	LocalStorage *LocalStorage `protobuf:"bytes,5,opt,name=local_storage,json=localStorage,proto3,oneof"`
}

func (*PhysicalBackupRequest_S3Storage) isPhysicalBackupRequest_StorageType() {}

func (*PhysicalBackupRequest_LocalStorage) isPhysicalBackupRequest_StorageType() {}

type RestoreRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	BackupFile string                 `protobuf:"bytes,1,opt,name=backup_file,json=backupFile,proto3" json:"backup_file,omitempty"`
	// Types that are valid to be assigned to StorageType:
	//
	//	*RestoreRequest_S3Storage
	//	*RestoreRequest_LocalStorage
	StorageType   isRestoreRequest_StorageType `protobuf_oneof:"StorageType"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreRequest) Reset() {
	*x = RestoreRequest{}
	mi := &file_pkg_agent_app_postgresql_pb_postgresql_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreRequest) ProtoMessage() {}

func (x *RestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_app_postgresql_pb_postgresql_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreRequest.ProtoReflect.Descriptor instead.
func (*RestoreRequest) Descriptor() ([]byte, []int) {
	return file_pkg_agent_app_postgresql_pb_postgresql_proto_rawDescGZIP(), []int{4}
}

func (x *RestoreRequest) GetBackupFile() string {
	if x != nil {
		return x.BackupFile
	}
	return ""
}

func (x *RestoreRequest) GetStorageType() isRestoreRequest_StorageType {
	if x != nil {
		return x.StorageType
	}
	return nil
}

func (x *RestoreRequest) GetS3Storage() *S3Storage {
	if x != nil {
		if x, ok := x.StorageType.(*RestoreRequest_S3Storage); ok {
			return x.S3Storage
		}
	}
	return nil
}

func (x *RestoreRequest) GetLocalStorage() *LocalStorage {
	if x != nil {
		if x, ok := x.StorageType.(*RestoreRequest_LocalStorage); ok {
			return x.LocalStorage
		}
	}
	return nil
}

type isRestoreRequest_StorageType interface {
	isRestoreRequest_StorageType()
}

type RestoreRequest_S3Storage struct {
	S3Storage *S3Storage `protobuf:"bytes,2,opt,name=s3_storage,json=s3Storage,proto3,oneof"`
}

type RestoreRequest_LocalStorage struct {
	LocalStorage *LocalStorage `protobuf:"bytes,3,opt,name=local_storage,json=localStorage,proto3,oneof"`
}

func (*RestoreRequest_S3Storage) isRestoreRequest_StorageType() {}

func (*RestoreRequest_LocalStorage) isRestoreRequest_StorageType() {}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_pkg_agent_app_postgresql_pb_postgresql_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_app_postgresql_pb_postgresql_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_pkg_agent_app_postgresql_pb_postgresql_proto_rawDescGZIP(), []int{5}
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pkg_agent_app_postgresql_pb_postgresql_proto protoreflect.FileDescriptor

const file_pkg_agent_app_postgresql_pb_postgresql_proto_rawDesc = "" +
	"\n" +
	",pkg/agent/app/postgresql/pb/postgresql.proto\x12\n" +
	"postgresql\"}\n" +
	"\tS3Storage\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12\x16\n" +
	"\x06bucket\x18\x02 \x01(\tR\x06bucket\x12\x1d\n" +
	"\n" +
	"access_key\x18\x03 \x01(\tR\taccessKey\x12\x1d\n" +
	"\n" +
	"secret_key\x18\x04 \x01(\tR\tsecretKey\"\"\n" +
	"\fLocalStorage\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\xf6\x02\n" +
	"\x14LogicalBackupRequest\x12\x1f\n" +
	"\vbackup_file\x18\x01 \x01(\tR\n" +
	"backupFile\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x1a\n" +
	"\bdatabase\x18\x04 \x01(\tR\bdatabase\x12\x14\n" +
	"\x05table\x18\x05 \x01(\tR\x05table\x12K\n" +
	"\x11logicalBackupMode\x18\x06 \x01(\x0e2\x1d.postgresql.LogicalBackupModeR\x11logicalBackupMode\x126\n" +
	"\n" +
	"s3_storage\x18\a \x01(\v2\x15.postgresql.S3StorageH\x00R\ts3Storage\x12?\n" +
	"\rlocal_storage\x18\b \x01(\v2\x18.postgresql.LocalStorageH\x00R\flocalStorageB\r\n" +
	"\vStorageType\"\xf8\x01\n" +
	"\x15PhysicalBackupRequest\x12\x1f\n" +
	"\vbackup_file\x18\x01 \x01(\tR\n" +
	"backupFile\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x126\n" +
	"\n" +
	"s3_storage\x18\x04 \x01(\v2\x15.postgresql.S3StorageH\x00R\ts3Storage\x12?\n" +
	"\rlocal_storage\x18\x05 \x01(\v2\x18.postgresql.LocalStorageH\x00R\flocalStorageB\r\n" +
	"\vStorageType\"\xb9\x01\n" +
	"\x0eRestoreRequest\x12\x1f\n" +
	"\vbackup_file\x18\x01 \x01(\tR\n" +
	"backupFile\x126\n" +
	"\n" +
	"s3_storage\x18\x02 \x01(\v2\x15.postgresql.S3StorageH\x00R\ts3Storage\x12?\n" +
	"\rlocal_storage\x18\x03 \x01(\v2\x18.postgresql.LocalStorageH\x00R\flocalStorageB\r\n" +
	"\vStorageType\"$\n" +
	"\bResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage*6\n" +
	"\x11LogicalBackupMode\x12\b\n" +
	"\x04Full\x10\x00\x12\f\n" +
	"\bDatabase\x10\x01\x12\t\n" +
	"\x05Table\x10\x022\xe6\x01\n" +
	"\x13PostgresqlOperation\x12I\n" +
	"\x0ePhysicalBackup\x12!.postgresql.PhysicalBackupRequest\x1a\x14.postgresql.Response\x12G\n" +
	"\rLogicalBackup\x12 .postgresql.LogicalBackupRequest\x1a\x14.postgresql.Response\x12;\n" +
	"\aRestore\x12\x1a.postgresql.RestoreRequest\x1a\x14.postgresql.ResponseB9Z7github.com/upmio/unit-operator/pkg/agent/app/postgresqlb\x06proto3"

var (
	file_pkg_agent_app_postgresql_pb_postgresql_proto_rawDescOnce sync.Once
	file_pkg_agent_app_postgresql_pb_postgresql_proto_rawDescData []byte
)

func file_pkg_agent_app_postgresql_pb_postgresql_proto_rawDescGZIP() []byte {
	file_pkg_agent_app_postgresql_pb_postgresql_proto_rawDescOnce.Do(func() {
		file_pkg_agent_app_postgresql_pb_postgresql_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_agent_app_postgresql_pb_postgresql_proto_rawDesc), len(file_pkg_agent_app_postgresql_pb_postgresql_proto_rawDesc)))
	})
	return file_pkg_agent_app_postgresql_pb_postgresql_proto_rawDescData
}

var file_pkg_agent_app_postgresql_pb_postgresql_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_agent_app_postgresql_pb_postgresql_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pkg_agent_app_postgresql_pb_postgresql_proto_goTypes = []any{
	(LogicalBackupMode)(0),        // 0: postgresql.LogicalBackupMode
	(*S3Storage)(nil),             // 1: postgresql.S3Storage
	(*LocalStorage)(nil),          // 2: postgresql.LocalStorage
	(*LogicalBackupRequest)(nil),  // 3: postgresql.LogicalBackupRequest
	(*PhysicalBackupRequest)(nil), // 4: postgresql.PhysicalBackupRequest
	(*RestoreRequest)(nil),        // 5: postgresql.RestoreRequest
	(*Response)(nil),              // 6: postgresql.Response
}
var file_pkg_agent_app_postgresql_pb_postgresql_proto_depIdxs = []int32{
	0,  // 0: postgresql.LogicalBackupRequest.logicalBackupMode:type_name -> postgresql.LogicalBackupMode
	1,  // 1: postgresql.LogicalBackupRequest.s3_storage:type_name -> postgresql.S3Storage
	2,  // 2: postgresql.LogicalBackupRequest.local_storage:type_name -> postgresql.LocalStorage
	1,  // 3: postgresql.PhysicalBackupRequest.s3_storage:type_name -> postgresql.S3Storage
	2,  // 4: postgresql.PhysicalBackupRequest.local_storage:type_name -> postgresql.LocalStorage
	1,  // 5: postgresql.RestoreRequest.s3_storage:type_name -> postgresql.S3Storage
	2,  // 6: postgresql.RestoreRequest.local_storage:type_name -> postgresql.LocalStorage
	4,  // 7: postgresql.PostgresqlOperation.PhysicalBackup:input_type -> postgresql.PhysicalBackupRequest
	3,  // 8: postgresql.PostgresqlOperation.LogicalBackup:input_type -> postgresql.LogicalBackupRequest
	5,  // 9: postgresql.PostgresqlOperation.Restore:input_type -> postgresql.RestoreRequest
	6,  // 10: postgresql.PostgresqlOperation.PhysicalBackup:output_type -> postgresql.Response
	6,  // 11: postgresql.PostgresqlOperation.LogicalBackup:output_type -> postgresql.Response
	6,  // 12: postgresql.PostgresqlOperation.Restore:output_type -> postgresql.Response
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_pkg_agent_app_postgresql_pb_postgresql_proto_init() }
func file_pkg_agent_app_postgresql_pb_postgresql_proto_init() {
	if File_pkg_agent_app_postgresql_pb_postgresql_proto != nil {
		return
	}
	file_pkg_agent_app_postgresql_pb_postgresql_proto_msgTypes[2].OneofWrappers = []any{
		(*LogicalBackupRequest_S3Storage)(nil),
		(*LogicalBackupRequest_LocalStorage)(nil),
	}
	file_pkg_agent_app_postgresql_pb_postgresql_proto_msgTypes[3].OneofWrappers = []any{
		(*PhysicalBackupRequest_S3Storage)(nil),
		(*PhysicalBackupRequest_LocalStorage)(nil),
	}
	file_pkg_agent_app_postgresql_pb_postgresql_proto_msgTypes[4].OneofWrappers = []any{
		(*RestoreRequest_S3Storage)(nil),
		(*RestoreRequest_LocalStorage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_agent_app_postgresql_pb_postgresql_proto_rawDesc), len(file_pkg_agent_app_postgresql_pb_postgresql_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_agent_app_postgresql_pb_postgresql_proto_goTypes,
		DependencyIndexes: file_pkg_agent_app_postgresql_pb_postgresql_proto_depIdxs,
		EnumInfos:         file_pkg_agent_app_postgresql_pb_postgresql_proto_enumTypes,
		MessageInfos:      file_pkg_agent_app_postgresql_pb_postgresql_proto_msgTypes,
	}.Build()
	File_pkg_agent_app_postgresql_pb_postgresql_proto = out.File
	file_pkg_agent_app_postgresql_pb_postgresql_proto_goTypes = nil
	file_pkg_agent_app_postgresql_pb_postgresql_proto_depIdxs = nil
}
