// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.0
// source: pkg/agent/app/sentinel/pb/sentinel.proto

package sentinel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateRedisReplicationRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	RedisReplicationName string                 `protobuf:"bytes,1,opt,name=redis_replication_name,json=redisReplicationName,proto3" json:"redis_replication_name,omitempty"`
	Namespace            string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	MasterHost           string                 `protobuf:"bytes,3,opt,name=master_host,json=masterHost,proto3" json:"master_host,omitempty"`
	SelfUnitName         string                 `protobuf:"bytes,4,opt,name=self_unit_name,json=selfUnitName,proto3" json:"self_unit_name,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UpdateRedisReplicationRequest) Reset() {
	*x = UpdateRedisReplicationRequest{}
	mi := &file_pkg_agent_app_sentinel_pb_sentinel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRedisReplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRedisReplicationRequest) ProtoMessage() {}

func (x *UpdateRedisReplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_app_sentinel_pb_sentinel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRedisReplicationRequest.ProtoReflect.Descriptor instead.
func (*UpdateRedisReplicationRequest) Descriptor() ([]byte, []int) {
	return file_pkg_agent_app_sentinel_pb_sentinel_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateRedisReplicationRequest) GetRedisReplicationName() string {
	if x != nil {
		return x.RedisReplicationName
	}
	return ""
}

func (x *UpdateRedisReplicationRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *UpdateRedisReplicationRequest) GetMasterHost() string {
	if x != nil {
		return x.MasterHost
	}
	return ""
}

func (x *UpdateRedisReplicationRequest) GetSelfUnitName() string {
	if x != nil {
		return x.SelfUnitName
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_pkg_agent_app_sentinel_pb_sentinel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_app_sentinel_pb_sentinel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_pkg_agent_app_sentinel_pb_sentinel_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pkg_agent_app_sentinel_pb_sentinel_proto protoreflect.FileDescriptor

const file_pkg_agent_app_sentinel_pb_sentinel_proto_rawDesc = "" +
	"\n" +
	"(pkg/agent/app/sentinel/pb/sentinel.proto\x12\bsentinel\"\xba\x01\n" +
	"\x1dUpdateRedisReplicationRequest\x124\n" +
	"\x16redis_replication_name\x18\x01 \x01(\tR\x14redisReplicationName\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1f\n" +
	"\vmaster_host\x18\x03 \x01(\tR\n" +
	"masterHost\x12$\n" +
	"\x0eself_unit_name\x18\x04 \x01(\tR\fselfUnitName\"$\n" +
	"\bResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2j\n" +
	"\x11SentinelOperation\x12U\n" +
	"\x16UpdateRedisReplication\x12'.sentinel.UpdateRedisReplicationRequest\x1a\x12.sentinel.ResponseB7Z5github.com/upmio/unit-operator/pkg/agent/app/sentinelb\x06proto3"

var (
	file_pkg_agent_app_sentinel_pb_sentinel_proto_rawDescOnce sync.Once
	file_pkg_agent_app_sentinel_pb_sentinel_proto_rawDescData []byte
)

func file_pkg_agent_app_sentinel_pb_sentinel_proto_rawDescGZIP() []byte {
	file_pkg_agent_app_sentinel_pb_sentinel_proto_rawDescOnce.Do(func() {
		file_pkg_agent_app_sentinel_pb_sentinel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_agent_app_sentinel_pb_sentinel_proto_rawDesc), len(file_pkg_agent_app_sentinel_pb_sentinel_proto_rawDesc)))
	})
	return file_pkg_agent_app_sentinel_pb_sentinel_proto_rawDescData
}

var file_pkg_agent_app_sentinel_pb_sentinel_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_agent_app_sentinel_pb_sentinel_proto_goTypes = []any{
	(*UpdateRedisReplicationRequest)(nil), // 0: sentinel.UpdateRedisReplicationRequest
	(*Response)(nil),                      // 1: sentinel.Response
}
var file_pkg_agent_app_sentinel_pb_sentinel_proto_depIdxs = []int32{
	0, // 0: sentinel.SentinelOperation.UpdateRedisReplication:input_type -> sentinel.UpdateRedisReplicationRequest
	1, // 1: sentinel.SentinelOperation.UpdateRedisReplication:output_type -> sentinel.Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_agent_app_sentinel_pb_sentinel_proto_init() }
func file_pkg_agent_app_sentinel_pb_sentinel_proto_init() {
	if File_pkg_agent_app_sentinel_pb_sentinel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_agent_app_sentinel_pb_sentinel_proto_rawDesc), len(file_pkg_agent_app_sentinel_pb_sentinel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_agent_app_sentinel_pb_sentinel_proto_goTypes,
		DependencyIndexes: file_pkg_agent_app_sentinel_pb_sentinel_proto_depIdxs,
		MessageInfos:      file_pkg_agent_app_sentinel_pb_sentinel_proto_msgTypes,
	}.Build()
	File_pkg_agent_app_sentinel_pb_sentinel_proto = out.File
	file_pkg_agent_app_sentinel_pb_sentinel_proto_goTypes = nil
	file_pkg_agent_app_sentinel_pb_sentinel_proto_depIdxs = nil
}
