// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.36.0
// source: pkg/agent/app/proxysql/pb/proxysql.proto

package proxysql

import (
	context "context"
	common "github.com/upmio/unit-operator/pkg/agent/app/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProxysqlOperation_SetVariable_FullMethodName = "/proxysql.ProxysqlOperation/SetVariable"
)

// ProxysqlOperationClient is the client API for ProxysqlOperation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProxysqlOperationClient interface {
	SetVariable(ctx context.Context, in *SetVariableRequest, opts ...grpc.CallOption) (*common.Empty, error)
}

type proxysqlOperationClient struct {
	cc grpc.ClientConnInterface
}

func NewProxysqlOperationClient(cc grpc.ClientConnInterface) ProxysqlOperationClient {
	return &proxysqlOperationClient{cc}
}

func (c *proxysqlOperationClient) SetVariable(ctx context.Context, in *SetVariableRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, ProxysqlOperation_SetVariable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProxysqlOperationServer is the server API for ProxysqlOperation service.
// All implementations must embed UnimplementedProxysqlOperationServer
// for forward compatibility.
type ProxysqlOperationServer interface {
	SetVariable(context.Context, *SetVariableRequest) (*common.Empty, error)
	mustEmbedUnimplementedProxysqlOperationServer()
}

// UnimplementedProxysqlOperationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProxysqlOperationServer struct{}

func (UnimplementedProxysqlOperationServer) SetVariable(context.Context, *SetVariableRequest) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetVariable not implemented")
}
func (UnimplementedProxysqlOperationServer) mustEmbedUnimplementedProxysqlOperationServer() {}
func (UnimplementedProxysqlOperationServer) testEmbeddedByValue()                           {}

// UnsafeProxysqlOperationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProxysqlOperationServer will
// result in compilation errors.
type UnsafeProxysqlOperationServer interface {
	mustEmbedUnimplementedProxysqlOperationServer()
}

func RegisterProxysqlOperationServer(s grpc.ServiceRegistrar, srv ProxysqlOperationServer) {
	// If the following call pancis, it indicates UnimplementedProxysqlOperationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProxysqlOperation_ServiceDesc, srv)
}

func _ProxysqlOperation_SetVariable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetVariableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxysqlOperationServer).SetVariable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxysqlOperation_SetVariable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxysqlOperationServer).SetVariable(ctx, req.(*SetVariableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProxysqlOperation_ServiceDesc is the grpc.ServiceDesc for ProxysqlOperation service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProxysqlOperation_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proxysql.ProxysqlOperation",
	HandlerType: (*ProxysqlOperationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetVariable",
			Handler:    _ProxysqlOperation_SetVariable_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/agent/app/proxysql/pb/proxysql.proto",
}
