// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.0
// source: pkg/agent/app/proxysql/pb/proxysql.proto

package proxysql

import (
	common "github.com/upmio/unit-operator/pkg/agent/app/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetVariableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Section       string                 `protobuf:"bytes,3,opt,name=section,proto3" json:"section,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetVariableRequest) Reset() {
	*x = SetVariableRequest{}
	mi := &file_pkg_agent_app_proxysql_pb_proxysql_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetVariableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetVariableRequest) ProtoMessage() {}

func (x *SetVariableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_app_proxysql_pb_proxysql_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetVariableRequest.ProtoReflect.Descriptor instead.
func (*SetVariableRequest) Descriptor() ([]byte, []int) {
	return file_pkg_agent_app_proxysql_pb_proxysql_proto_rawDescGZIP(), []int{0}
}

func (x *SetVariableRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetVariableRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SetVariableRequest) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

func (x *SetVariableRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

var File_pkg_agent_app_proxysql_pb_proxysql_proto protoreflect.FileDescriptor

const file_pkg_agent_app_proxysql_pb_proxysql_proto_rawDesc = "" +
	"\n" +
	"(pkg/agent/app/proxysql/pb/proxysql.proto\x12\bproxysql\x1a$pkg/agent/app/common/pb/common.proto\"r\n" +
	"\x12SetVariableRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x18\n" +
	"\asection\x18\x03 \x01(\tR\asection\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername2O\n" +
	"\x11ProxysqlOperation\x12:\n" +
	"\vSetVariable\x12\x1c.proxysql.SetVariableRequest\x1a\r.common.EmptyB7Z5github.com/upmio/unit-operator/pkg/agent/app/proxysqlb\x06proto3"

var (
	file_pkg_agent_app_proxysql_pb_proxysql_proto_rawDescOnce sync.Once
	file_pkg_agent_app_proxysql_pb_proxysql_proto_rawDescData []byte
)

func file_pkg_agent_app_proxysql_pb_proxysql_proto_rawDescGZIP() []byte {
	file_pkg_agent_app_proxysql_pb_proxysql_proto_rawDescOnce.Do(func() {
		file_pkg_agent_app_proxysql_pb_proxysql_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_agent_app_proxysql_pb_proxysql_proto_rawDesc), len(file_pkg_agent_app_proxysql_pb_proxysql_proto_rawDesc)))
	})
	return file_pkg_agent_app_proxysql_pb_proxysql_proto_rawDescData
}

var file_pkg_agent_app_proxysql_pb_proxysql_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_agent_app_proxysql_pb_proxysql_proto_goTypes = []any{
	(*SetVariableRequest)(nil), // 0: proxysql.SetVariableRequest
	(*common.Empty)(nil),       // 1: common.Empty
}
var file_pkg_agent_app_proxysql_pb_proxysql_proto_depIdxs = []int32{
	0, // 0: proxysql.ProxysqlOperation.SetVariable:input_type -> proxysql.SetVariableRequest
	1, // 1: proxysql.ProxysqlOperation.SetVariable:output_type -> common.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_agent_app_proxysql_pb_proxysql_proto_init() }
func file_pkg_agent_app_proxysql_pb_proxysql_proto_init() {
	if File_pkg_agent_app_proxysql_pb_proxysql_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_agent_app_proxysql_pb_proxysql_proto_rawDesc), len(file_pkg_agent_app_proxysql_pb_proxysql_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_agent_app_proxysql_pb_proxysql_proto_goTypes,
		DependencyIndexes: file_pkg_agent_app_proxysql_pb_proxysql_proto_depIdxs,
		MessageInfos:      file_pkg_agent_app_proxysql_pb_proxysql_proto_msgTypes,
	}.Build()
	File_pkg_agent_app_proxysql_pb_proxysql_proto = out.File
	file_pkg_agent_app_proxysql_pb_proxysql_proto_goTypes = nil
	file_pkg_agent_app_proxysql_pb_proxysql_proto_depIdxs = nil
}
