// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0
// source: pkg/agent/app/hugegraphhubble/pb/hugegraphhubble.proto

package hugegraphhubble

import (
	common "github.com/upmio/unit-operator/pkg/agent/app/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfigureGraphConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Graph         string                 `protobuf:"bytes,2,opt,name=graph,proto3" json:"graph,omitempty"`
	Host          string                 `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureGraphConnectionRequest) Reset() {
	*x = ConfigureGraphConnectionRequest{}
	mi := &file_pkg_agent_app_hugegraphhubble_pb_hugegraphhubble_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureGraphConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureGraphConnectionRequest) ProtoMessage() {}

func (x *ConfigureGraphConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_app_hugegraphhubble_pb_hugegraphhubble_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureGraphConnectionRequest.ProtoReflect.Descriptor instead.
func (*ConfigureGraphConnectionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_agent_app_hugegraphhubble_pb_hugegraphhubble_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigureGraphConnectionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConfigureGraphConnectionRequest) GetGraph() string {
	if x != nil {
		return x.Graph
	}
	return ""
}

func (x *ConfigureGraphConnectionRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ConfigureGraphConnectionRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

var File_pkg_agent_app_hugegraphhubble_pb_hugegraphhubble_proto protoreflect.FileDescriptor

const file_pkg_agent_app_hugegraphhubble_pb_hugegraphhubble_proto_rawDesc = "" +
	"\n" +
	"6pkg/agent/app/hugegraphhubble/pb/hugegraphhubble.proto\x12\x0fhugegraphhubble\x1a$pkg/agent/app/common/pb/common.proto\"s\n" +
	"\x1fConfigureGraphConnectionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05graph\x18\x02 \x01(\tR\x05graph\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port2w\n" +
	"\x18HugeGraphHubbleOperation\x12[\n" +
	"\x18ConfigureGraphConnection\x120.hugegraphhubble.ConfigureGraphConnectionRequest\x1a\r.common.EmptyB>Z<github.com/upmio/unit-operator/pkg/agent/app/hugegraphhubbleb\x06proto3"

var (
	file_pkg_agent_app_hugegraphhubble_pb_hugegraphhubble_proto_rawDescOnce sync.Once
	file_pkg_agent_app_hugegraphhubble_pb_hugegraphhubble_proto_rawDescData []byte
)

func file_pkg_agent_app_hugegraphhubble_pb_hugegraphhubble_proto_rawDescGZIP() []byte {
	file_pkg_agent_app_hugegraphhubble_pb_hugegraphhubble_proto_rawDescOnce.Do(func() {
		file_pkg_agent_app_hugegraphhubble_pb_hugegraphhubble_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_agent_app_hugegraphhubble_pb_hugegraphhubble_proto_rawDesc), len(file_pkg_agent_app_hugegraphhubble_pb_hugegraphhubble_proto_rawDesc)))
	})
	return file_pkg_agent_app_hugegraphhubble_pb_hugegraphhubble_proto_rawDescData
}

var file_pkg_agent_app_hugegraphhubble_pb_hugegraphhubble_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_agent_app_hugegraphhubble_pb_hugegraphhubble_proto_goTypes = []any{
	(*ConfigureGraphConnectionRequest)(nil), // 0: hugegraphhubble.ConfigureGraphConnectionRequest
	(*common.Empty)(nil),                    // 1: common.Empty
}
var file_pkg_agent_app_hugegraphhubble_pb_hugegraphhubble_proto_depIdxs = []int32{
	0, // 0: hugegraphhubble.HugeGraphHubbleOperation.ConfigureGraphConnection:input_type -> hugegraphhubble.ConfigureGraphConnectionRequest
	1, // 1: hugegraphhubble.HugeGraphHubbleOperation.ConfigureGraphConnection:output_type -> common.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_agent_app_hugegraphhubble_pb_hugegraphhubble_proto_init() }
func file_pkg_agent_app_hugegraphhubble_pb_hugegraphhubble_proto_init() {
	if File_pkg_agent_app_hugegraphhubble_pb_hugegraphhubble_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_agent_app_hugegraphhubble_pb_hugegraphhubble_proto_rawDesc), len(file_pkg_agent_app_hugegraphhubble_pb_hugegraphhubble_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_agent_app_hugegraphhubble_pb_hugegraphhubble_proto_goTypes,
		DependencyIndexes: file_pkg_agent_app_hugegraphhubble_pb_hugegraphhubble_proto_depIdxs,
		MessageInfos:      file_pkg_agent_app_hugegraphhubble_pb_hugegraphhubble_proto_msgTypes,
	}.Build()
	File_pkg_agent_app_hugegraphhubble_pb_hugegraphhubble_proto = out.File
	file_pkg_agent_app_hugegraphhubble_pb_hugegraphhubble_proto_goTypes = nil
	file_pkg_agent_app_hugegraphhubble_pb_hugegraphhubble_proto_depIdxs = nil
}
