// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.36.0
// source: pkg/agent/app/hugegraphhubble/pb/hugegraphhubble.proto

package hugegraphhubble

import (
	context "context"
	common "github.com/upmio/unit-operator/pkg/agent/app/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HugeGraphHubbleOperation_ConfigureGraphConnection_FullMethodName = "/hugegraphhubble.HugeGraphHubbleOperation/ConfigureGraphConnection"
	HugeGraphHubbleOperation_Backup_FullMethodName                   = "/hugegraphhubble.HugeGraphHubbleOperation/Backup"
	HugeGraphHubbleOperation_Restore_FullMethodName                  = "/hugegraphhubble.HugeGraphHubbleOperation/Restore"
)

// HugeGraphHubbleOperationClient is the client API for HugeGraphHubbleOperation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HugeGraphHubbleOperationClient interface {
	ConfigureGraphConnection(ctx context.Context, in *ConfigureGraphConnectionRequest, opts ...grpc.CallOption) (*common.Empty, error)
	Backup(ctx context.Context, in *BackupRequest, opts ...grpc.CallOption) (*common.Empty, error)
	Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*common.Empty, error)
}

type hugeGraphHubbleOperationClient struct {
	cc grpc.ClientConnInterface
}

func NewHugeGraphHubbleOperationClient(cc grpc.ClientConnInterface) HugeGraphHubbleOperationClient {
	return &hugeGraphHubbleOperationClient{cc}
}

func (c *hugeGraphHubbleOperationClient) ConfigureGraphConnection(ctx context.Context, in *ConfigureGraphConnectionRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, HugeGraphHubbleOperation_ConfigureGraphConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hugeGraphHubbleOperationClient) Backup(ctx context.Context, in *BackupRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, HugeGraphHubbleOperation_Backup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hugeGraphHubbleOperationClient) Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, HugeGraphHubbleOperation_Restore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HugeGraphHubbleOperationServer is the server API for HugeGraphHubbleOperation service.
// All implementations must embed UnimplementedHugeGraphHubbleOperationServer
// for forward compatibility.
type HugeGraphHubbleOperationServer interface {
	ConfigureGraphConnection(context.Context, *ConfigureGraphConnectionRequest) (*common.Empty, error)
	Backup(context.Context, *BackupRequest) (*common.Empty, error)
	Restore(context.Context, *RestoreRequest) (*common.Empty, error)
	mustEmbedUnimplementedHugeGraphHubbleOperationServer()
}

// UnimplementedHugeGraphHubbleOperationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHugeGraphHubbleOperationServer struct{}

func (UnimplementedHugeGraphHubbleOperationServer) ConfigureGraphConnection(context.Context, *ConfigureGraphConnectionRequest) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfigureGraphConnection not implemented")
}
func (UnimplementedHugeGraphHubbleOperationServer) Backup(context.Context, *BackupRequest) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Backup not implemented")
}
func (UnimplementedHugeGraphHubbleOperationServer) Restore(context.Context, *RestoreRequest) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Restore not implemented")
}
func (UnimplementedHugeGraphHubbleOperationServer) mustEmbedUnimplementedHugeGraphHubbleOperationServer() {
}
func (UnimplementedHugeGraphHubbleOperationServer) testEmbeddedByValue() {}

// UnsafeHugeGraphHubbleOperationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HugeGraphHubbleOperationServer will
// result in compilation errors.
type UnsafeHugeGraphHubbleOperationServer interface {
	mustEmbedUnimplementedHugeGraphHubbleOperationServer()
}

func RegisterHugeGraphHubbleOperationServer(s grpc.ServiceRegistrar, srv HugeGraphHubbleOperationServer) {
	// If the following call pancis, it indicates UnimplementedHugeGraphHubbleOperationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HugeGraphHubbleOperation_ServiceDesc, srv)
}

func _HugeGraphHubbleOperation_ConfigureGraphConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureGraphConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HugeGraphHubbleOperationServer).ConfigureGraphConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HugeGraphHubbleOperation_ConfigureGraphConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HugeGraphHubbleOperationServer).ConfigureGraphConnection(ctx, req.(*ConfigureGraphConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HugeGraphHubbleOperation_Backup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HugeGraphHubbleOperationServer).Backup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HugeGraphHubbleOperation_Backup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HugeGraphHubbleOperationServer).Backup(ctx, req.(*BackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HugeGraphHubbleOperation_Restore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HugeGraphHubbleOperationServer).Restore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HugeGraphHubbleOperation_Restore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HugeGraphHubbleOperationServer).Restore(ctx, req.(*RestoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HugeGraphHubbleOperation_ServiceDesc is the grpc.ServiceDesc for HugeGraphHubbleOperation service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HugeGraphHubbleOperation_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hugegraphhubble.HugeGraphHubbleOperation",
	HandlerType: (*HugeGraphHubbleOperationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConfigureGraphConnection",
			Handler:    _HugeGraphHubbleOperation_ConfigureGraphConnection_Handler,
		},
		{
			MethodName: "Backup",
			Handler:    _HugeGraphHubbleOperation_Backup_Handler,
		},
		{
			MethodName: "Restore",
			Handler:    _HugeGraphHubbleOperation_Restore_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/agent/app/hugegraphhubble/pb/hugegraphhubble.proto",
}
