// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.0
// source: pkg/agent/app/slm/pb/slm.proto

package slm

import (
	common "github.com/upmio/unit-operator/pkg/agent/app/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_pkg_agent_app_slm_pb_slm_proto protoreflect.FileDescriptor

const file_pkg_agent_app_slm_pb_slm_proto_rawDesc = "" +
	"\n" +
	"\x1epkg/agent/app/slm/pb/slm.proto\x12\aservice\x1a$pkg/agent/app/common/pb/common.proto2\x87\x02\n" +
	"\x10ServiceLifecycle\x12,\n" +
	"\fStartProcess\x12\r.common.Empty\x1a\r.common.Empty\x12+\n" +
	"\vStopProcess\x12\r.common.Empty\x1a\r.common.Empty\x12.\n" +
	"\x0eRestartProcess\x12\r.common.Empty\x1a\r.common.Empty\x123\n" +
	"\x13CheckProcessStarted\x12\r.common.Empty\x1a\r.common.Empty\x123\n" +
	"\x13CheckProcessStopped\x12\r.common.Empty\x1a\r.common.EmptyB2Z0github.com/upmio/unit-operator/pkg/agent/app/slmb\x06proto3"

var file_pkg_agent_app_slm_pb_slm_proto_goTypes = []any{
	(*common.Empty)(nil), // 0: common.Empty
}
var file_pkg_agent_app_slm_pb_slm_proto_depIdxs = []int32{
	0, // 0: service.ServiceLifecycle.StartProcess:input_type -> common.Empty
	0, // 1: service.ServiceLifecycle.StopProcess:input_type -> common.Empty
	0, // 2: service.ServiceLifecycle.RestartProcess:input_type -> common.Empty
	0, // 3: service.ServiceLifecycle.CheckProcessStarted:input_type -> common.Empty
	0, // 4: service.ServiceLifecycle.CheckProcessStopped:input_type -> common.Empty
	0, // 5: service.ServiceLifecycle.StartProcess:output_type -> common.Empty
	0, // 6: service.ServiceLifecycle.StopProcess:output_type -> common.Empty
	0, // 7: service.ServiceLifecycle.RestartProcess:output_type -> common.Empty
	0, // 8: service.ServiceLifecycle.CheckProcessStarted:output_type -> common.Empty
	0, // 9: service.ServiceLifecycle.CheckProcessStopped:output_type -> common.Empty
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_agent_app_slm_pb_slm_proto_init() }
func file_pkg_agent_app_slm_pb_slm_proto_init() {
	if File_pkg_agent_app_slm_pb_slm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_agent_app_slm_pb_slm_proto_rawDesc), len(file_pkg_agent_app_slm_pb_slm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_agent_app_slm_pb_slm_proto_goTypes,
		DependencyIndexes: file_pkg_agent_app_slm_pb_slm_proto_depIdxs,
	}.Build()
	File_pkg_agent_app_slm_pb_slm_proto = out.File
	file_pkg_agent_app_slm_pb_slm_proto_goTypes = nil
	file_pkg_agent_app_slm_pb_slm_proto_depIdxs = nil
}
