// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.36.0
// source: pkg/agent/app/slm/pb/slm.proto

package slm

import (
	context "context"
	common "github.com/upmio/unit-operator/pkg/agent/app/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ServiceLifecycle_StartProcess_FullMethodName        = "/service.ServiceLifecycle/StartProcess"
	ServiceLifecycle_StopProcess_FullMethodName         = "/service.ServiceLifecycle/StopProcess"
	ServiceLifecycle_RestartProcess_FullMethodName      = "/service.ServiceLifecycle/RestartProcess"
	ServiceLifecycle_CheckProcessStarted_FullMethodName = "/service.ServiceLifecycle/CheckProcessStarted"
	ServiceLifecycle_CheckProcessStopped_FullMethodName = "/service.ServiceLifecycle/CheckProcessStopped"
)

// ServiceLifecycleClient is the client API for ServiceLifecycle service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceLifecycleClient interface {
	StartProcess(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*common.Empty, error)
	StopProcess(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*common.Empty, error)
	RestartProcess(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*common.Empty, error)
	CheckProcessStarted(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*common.Empty, error)
	CheckProcessStopped(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*common.Empty, error)
}

type serviceLifecycleClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceLifecycleClient(cc grpc.ClientConnInterface) ServiceLifecycleClient {
	return &serviceLifecycleClient{cc}
}

func (c *serviceLifecycleClient) StartProcess(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*common.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, ServiceLifecycle_StartProcess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceLifecycleClient) StopProcess(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*common.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, ServiceLifecycle_StopProcess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceLifecycleClient) RestartProcess(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*common.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, ServiceLifecycle_RestartProcess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceLifecycleClient) CheckProcessStarted(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*common.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, ServiceLifecycle_CheckProcessStarted_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceLifecycleClient) CheckProcessStopped(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*common.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, ServiceLifecycle_CheckProcessStopped_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceLifecycleServer is the server API for ServiceLifecycle service.
// All implementations must embed UnimplementedServiceLifecycleServer
// for forward compatibility.
type ServiceLifecycleServer interface {
	StartProcess(context.Context, *common.Empty) (*common.Empty, error)
	StopProcess(context.Context, *common.Empty) (*common.Empty, error)
	RestartProcess(context.Context, *common.Empty) (*common.Empty, error)
	CheckProcessStarted(context.Context, *common.Empty) (*common.Empty, error)
	CheckProcessStopped(context.Context, *common.Empty) (*common.Empty, error)
	mustEmbedUnimplementedServiceLifecycleServer()
}

// UnimplementedServiceLifecycleServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServiceLifecycleServer struct{}

func (UnimplementedServiceLifecycleServer) StartProcess(context.Context, *common.Empty) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartProcess not implemented")
}
func (UnimplementedServiceLifecycleServer) StopProcess(context.Context, *common.Empty) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopProcess not implemented")
}
func (UnimplementedServiceLifecycleServer) RestartProcess(context.Context, *common.Empty) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestartProcess not implemented")
}
func (UnimplementedServiceLifecycleServer) CheckProcessStarted(context.Context, *common.Empty) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckProcessStarted not implemented")
}
func (UnimplementedServiceLifecycleServer) CheckProcessStopped(context.Context, *common.Empty) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckProcessStopped not implemented")
}
func (UnimplementedServiceLifecycleServer) mustEmbedUnimplementedServiceLifecycleServer() {}
func (UnimplementedServiceLifecycleServer) testEmbeddedByValue()                          {}

// UnsafeServiceLifecycleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceLifecycleServer will
// result in compilation errors.
type UnsafeServiceLifecycleServer interface {
	mustEmbedUnimplementedServiceLifecycleServer()
}

func RegisterServiceLifecycleServer(s grpc.ServiceRegistrar, srv ServiceLifecycleServer) {
	// If the following call pancis, it indicates UnimplementedServiceLifecycleServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ServiceLifecycle_ServiceDesc, srv)
}

func _ServiceLifecycle_StartProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceLifecycleServer).StartProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceLifecycle_StartProcess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceLifecycleServer).StartProcess(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceLifecycle_StopProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceLifecycleServer).StopProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceLifecycle_StopProcess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceLifecycleServer).StopProcess(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceLifecycle_RestartProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceLifecycleServer).RestartProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceLifecycle_RestartProcess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceLifecycleServer).RestartProcess(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceLifecycle_CheckProcessStarted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceLifecycleServer).CheckProcessStarted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceLifecycle_CheckProcessStarted_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceLifecycleServer).CheckProcessStarted(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceLifecycle_CheckProcessStopped_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceLifecycleServer).CheckProcessStopped(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceLifecycle_CheckProcessStopped_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceLifecycleServer).CheckProcessStopped(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ServiceLifecycle_ServiceDesc is the grpc.ServiceDesc for ServiceLifecycle service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServiceLifecycle_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.ServiceLifecycle",
	HandlerType: (*ServiceLifecycleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartProcess",
			Handler:    _ServiceLifecycle_StartProcess_Handler,
		},
		{
			MethodName: "StopProcess",
			Handler:    _ServiceLifecycle_StopProcess_Handler,
		},
		{
			MethodName: "RestartProcess",
			Handler:    _ServiceLifecycle_RestartProcess_Handler,
		},
		{
			MethodName: "CheckProcessStarted",
			Handler:    _ServiceLifecycle_CheckProcessStarted_Handler,
		},
		{
			MethodName: "CheckProcessStopped",
			Handler:    _ServiceLifecycle_CheckProcessStopped_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/agent/app/slm/pb/slm.proto",
}
