# Description: This is an example of a UnitSet that deploys a PostgreSQL version 15.12.
# UnitSet CRD from the unit-operator is used to create the PostgreSQL service group.
# The UnitSet creates a PostgreSQL service group with 3 PostgreSQL units using steam replication mode to synchronize data between the two PostgreSQL instances.
# The PostgreSQL service group is created using the shared configuration ConfigMap and the secret.
# MysqlReplication CRD from the compose-operator is used to create the PostgreSQL Data Replication.
# The MysqlReplication will manage the replication between the units of the PostgreSQL service group.

# Secret is used to store the credentials for the PostgreSQL service group.
# The secret contains the following
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    upm.api/service-group.name: ustest
    upm.api/service-group.type: postgresql-sg
    upm.io/owner: upm
  name: postgresql-sg-ustest-secret
  namespace: test
data:
  # Remote administrator user, used to manage the database with all privileges. Plaintext password is 'Y4&7@6!@A7f!i!t0'
  helix: SmNOT0tEY0Y3ZnM3aUpWajlWSDRiOVV0WjQrc01ldHB1MnJsUnJ4NG1kWT0=
  # monitor user, used to monitor the database. Plaintext password is 'hwkfEfrw3v@@5N3@'
  monitor: WXErRzMreWx6ajUwVTlzQWovQStiOHU3UHhEL000NVo2R2pSRCs3RW9Xcz0=
  # replication user, used to support replication. Plaintext password is 'I5@b&@@75h@68f!q'
  replication: V1Y2MVZyZFRjbEVuT1lkbEx0R1c5cTljUmd0UjZubTlOM05aZkw2NkRxbz0=
  # local administrator user, used to manage the database with all privileges. Plaintext password is '7aW&te9m8b3y!tcm'
  postgres: VjVyOExqQmxyM3N2ODNsUHVrbmhDK29KZGRRQXl1dzlOWTJmNEJ6djdoRT0=
type: Opaque

# ConfigMap is used to store the shared configuration for the PostgreSQL service group.
# The ConfigMap contains the following
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    upm.api/service-group.name: ustest
    upm.api/service-group.type: postgresql-sg
    upm.io/owner: upm
  name: postgresql-sg-ustest-sharedconfigmap
  namespace: test
data:
  service_group_uid: "6fa3ca2a-0ffd-4ca7-8615-e2589f7dd413" # Unique identifier for the service group
  postgresql_ports: '[{"name": "postgresql", "containerPort": "5432","protocol": "TCP"}]' # Ports used by postgresql
# UnitSet is used to create the PostgreSQL service group and the PostgreSQL Replication service group.
# The UnitSet contains the following
---
apiVersion: upm.syntropycloud.io/v1alpha2
kind: UnitSet
metadata:
  # finalizers are used to delete the resources created by the UnitSet
  # upm.io/unit-delete will delete the Units
  # upm.io/configmap-delete will delete the ConfigMap
  finalizers:
    - upm.io/unit-delete
    - upm.io/configmap-delete
  # labels are used to filter the resources
  # upm.api/service-group.name: <service-group-name>
  # upm.api/service-group.type: <service-group-type>
  # upm.api/service.type: <service-type>
  # upm.io/owner: <owner>
  labels:
    upm.api/service-group.name: ustest
    upm.api/service-group.type: postgresql-sg
    upm.api/service.type: postgresql
    upm.io/owner: upm
  # name rule is <service-group-name>-<service-type>-<random-string>
  name: ustest-postgresql-foo
  namespace: test
spec:
  type: postgresql
  version:  "15.12"
  units: 3
  # sharedConfigName is the name of the ConfigMap that contains the shared configuration
  # upm-api-server will create this ConfigMap in the same namespace as the UnitSet
  sharedConfigName: postgresql-sg-ustest-sharedconfigmap
  # resources are used to set the resource limits and requests for postgresql container in the Unit
  resources:
    limits:
      cpu: "1"
      memory: 2Gi
    requests:
      cpu: "1"
      memory: 1Gi
  # storages and emptyDir are used to specify the volume type of Unit's data directory and log directory. You can only choose one way to define the volume type.
  # storages is used to create a persistent volume for the postgresql container in the Unit
  # mountPath is the path where the storage is mounted in the container
  # size is the size of the storage
  # storageClassName is the name of the storage class
  # storages:
  #   - name: data
  #     mountPath: /DATA_MOUNT
  #     size: 10Gi
  #     storageClassName: openebs-lvmsc-hdd
  #   - name: log
  #     mountPath: /LOG_MOUNT
  #     size: 10Gi
  #     storageClassName: openebs-lvmsc-hdd
  # emptyDir is a temporary directory that is initially empty, created when a Pod is assigned to a node and automatically deleted when the Pod is deleted.
  # emptyDir is used to create an empty directory in the postgresql container in the Unit
  emptyDir:
    - name: data
      mountPath: /DATA_MOUNT
      size: 5Gi
    - name: log
      mountPath: /LOG_MOUNT
      size: 5Gi
  # secret is used to mount the secret in the Unit
  secret:
    mountPath: /SECRET_MOUNT
    name: postgresql-sg-ustest-secret
  # Additional Service configuration, used to set external access, type optional values are NodePort, LoadBalancer
  # externalService:
  #   type: NodePort
  env:
    - name: ADM_USER
      value: postgres
    - name: MON_USER
      value: monitor
    - name: REPL_USER
      value: replication
  nodeAffinityPreset:
    # Used to set node affinity to ensure that postgresql is deployed on the specified node. kubernetes.io/arch amd64 means deployed on the node of the amd64 architecture.
    - key: kubernetes.io/arch
      values:
        - amd64
    # Used to set node affinity to ensure that postgresql is deployed on the specified node. upm.api/software.postgresql means deployed on the node with the software.postgresql label.
    - key: upm.api/software.postgresql
      values:
        - "true"
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 0
      partition: 0
    type: ""

# PostgresReplication CRD from the compose-operator is used to create the PostgreSQL Data Replication.
# The PostgresReplication will manage the replication between the units of the PostgreSQL service group.
# The PostgresReplication contains the following
---
apiVersion: upm.syntropycloud.io/v1alpha1
kind: PostgresReplication
metadata:
  labels:
    upm.api/service-group.name: ustest
    upm.api/service-group.type: postgresql-sg
    upm.api/service.name: ustest-postgresql-foo
    upm.io/owner: upm
  name: ustest-postgresql-foo-replication
  namespace: test
spec:
  # mode is used to set the replication mode, optional values are rpl_async, rpl_sync
  mode: rpl_sync
  secret:
    name: postgresql-sg-ustest-secret
    # 'postgres' is the key in the Secret used to specify the user managing the replication relationship.
    # The Manage Replication User is a special account designed for the master library in the PostgreSQL stream replication architecture.
    # This user role is SUPER.
    postgres: postgres
    # 'replication' is used to specify a user that supports replication.
    # The Replication User is a special account designed for slave libraries in the PostgreSQL stream replication architecture.
    # This user role is REPLICATION.
    replication: replication
  # Specify the instance name and port of the primary database
  primary:
    name: ustest-postgresql-foo-0
    host: ustest-postgresql-foo-0.ustest-postgresql-foo-headless-svc.test
    port: 5432
  # Specify the instance name and port of the secondary database
  standby:
    - name: ustest-postgresql-foo-1
      host: ustest-postgresql-foo-1.ustest-postgresql-foo-headless-svc.test
      port: 5432
    - name: ustest-postgresql-foo-2
      host: ustest-postgresql-foo-2.ustest-postgresql-foo-headless-svc.test
      port: 5432
  # Specifies the type of external access service. Optional values are NodePort, LoadBalancer.
  service:
    type: NodePort

# If you want to delete the resources created by the UnitSet, you can use the following commands
# kubectl delete secret -n test postgresql-sg-ustest-secret; kubectl delete configmaps -n test postgresql-sg-ustest-sharedconfigmap; kubectl delete PostgresReplication -n test ustest-postgresql-foo-replication; kubectl delete unitsets -n test ustest-postgresql-foo
