// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.0
// source: pkg/agent/app/config/pb/config.proto

package config

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncConfigRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Namespace             string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	TemplateConfigmapName string                 `protobuf:"bytes,2,opt,name=template_configmap_name,json=templateConfigmapName,proto3" json:"template_configmap_name,omitempty"`
	ValueConfigmapName    string                 `protobuf:"bytes,3,opt,name=value_configmap_name,json=valueConfigmapName,proto3" json:"value_configmap_name,omitempty"`
	Key                   string                 `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	ExtendValueConfigmaps []string               `protobuf:"bytes,5,rep,name=extend_value_configmaps,json=extendValueConfigmaps,proto3" json:"extend_value_configmaps,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SyncConfigRequest) Reset() {
	*x = SyncConfigRequest{}
	mi := &file_pkg_agent_app_config_pb_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncConfigRequest) ProtoMessage() {}

func (x *SyncConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_app_config_pb_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncConfigRequest.ProtoReflect.Descriptor instead.
func (*SyncConfigRequest) Descriptor() ([]byte, []int) {
	return file_pkg_agent_app_config_pb_config_proto_rawDescGZIP(), []int{0}
}

func (x *SyncConfigRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *SyncConfigRequest) GetTemplateConfigmapName() string {
	if x != nil {
		return x.TemplateConfigmapName
	}
	return ""
}

func (x *SyncConfigRequest) GetValueConfigmapName() string {
	if x != nil {
		return x.ValueConfigmapName
	}
	return ""
}

func (x *SyncConfigRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SyncConfigRequest) GetExtendValueConfigmaps() []string {
	if x != nil {
		return x.ExtendValueConfigmaps
	}
	return nil
}

type RewriteConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigmapName string                 `protobuf:"bytes,1,opt,name=configmap_name,json=configmapName,proto3" json:"configmap_name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RewriteConfigRequest) Reset() {
	*x = RewriteConfigRequest{}
	mi := &file_pkg_agent_app_config_pb_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RewriteConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewriteConfigRequest) ProtoMessage() {}

func (x *RewriteConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_app_config_pb_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewriteConfigRequest.ProtoReflect.Descriptor instead.
func (*RewriteConfigRequest) Descriptor() ([]byte, []int) {
	return file_pkg_agent_app_config_pb_config_proto_rawDescGZIP(), []int{1}
}

func (x *RewriteConfigRequest) GetConfigmapName() string {
	if x != nil {
		return x.ConfigmapName
	}
	return ""
}

func (x *RewriteConfigRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RewriteConfigRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RewriteConfigRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_pkg_agent_app_config_pb_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_app_config_pb_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_pkg_agent_app_config_pb_config_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pkg_agent_app_config_pb_config_proto protoreflect.FileDescriptor

const file_pkg_agent_app_config_pb_config_proto_rawDesc = "" +
	"\n" +
	"$pkg/agent/app/config/pb/config.proto\x12\x06config\"\xe5\x01\n" +
	"\x11SyncConfigRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x126\n" +
	"\x17template_configmap_name\x18\x02 \x01(\tR\x15templateConfigmapName\x120\n" +
	"\x14value_configmap_name\x18\x03 \x01(\tR\x12valueConfigmapName\x12\x10\n" +
	"\x03key\x18\x04 \x01(\tR\x03key\x126\n" +
	"\x17extend_value_configmaps\x18\x05 \x03(\tR\x15extendValueConfigmaps\"\x83\x01\n" +
	"\x14RewriteConfigRequest\x12%\n" +
	"\x0econfigmap_name\x18\x01 \x01(\tR\rconfigmapName\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\"$\n" +
	"\bResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\x8f\x01\n" +
	"\x11SyncConfigService\x129\n" +
	"\n" +
	"SyncConfig\x12\x19.config.SyncConfigRequest\x1a\x10.config.Response\x12?\n" +
	"\rRewriteConfig\x12\x1c.config.RewriteConfigRequest\x1a\x10.config.ResponseB5Z3github.com/upmio/unit-operator/pkg/agent/app/configb\x06proto3"

var (
	file_pkg_agent_app_config_pb_config_proto_rawDescOnce sync.Once
	file_pkg_agent_app_config_pb_config_proto_rawDescData []byte
)

func file_pkg_agent_app_config_pb_config_proto_rawDescGZIP() []byte {
	file_pkg_agent_app_config_pb_config_proto_rawDescOnce.Do(func() {
		file_pkg_agent_app_config_pb_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_agent_app_config_pb_config_proto_rawDesc), len(file_pkg_agent_app_config_pb_config_proto_rawDesc)))
	})
	return file_pkg_agent_app_config_pb_config_proto_rawDescData
}

var file_pkg_agent_app_config_pb_config_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_agent_app_config_pb_config_proto_goTypes = []any{
	(*SyncConfigRequest)(nil),    // 0: config.SyncConfigRequest
	(*RewriteConfigRequest)(nil), // 1: config.RewriteConfigRequest
	(*Response)(nil),             // 2: config.Response
}
var file_pkg_agent_app_config_pb_config_proto_depIdxs = []int32{
	0, // 0: config.SyncConfigService.SyncConfig:input_type -> config.SyncConfigRequest
	1, // 1: config.SyncConfigService.RewriteConfig:input_type -> config.RewriteConfigRequest
	2, // 2: config.SyncConfigService.SyncConfig:output_type -> config.Response
	2, // 3: config.SyncConfigService.RewriteConfig:output_type -> config.Response
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_agent_app_config_pb_config_proto_init() }
func file_pkg_agent_app_config_pb_config_proto_init() {
	if File_pkg_agent_app_config_pb_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_agent_app_config_pb_config_proto_rawDesc), len(file_pkg_agent_app_config_pb_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_agent_app_config_pb_config_proto_goTypes,
		DependencyIndexes: file_pkg_agent_app_config_pb_config_proto_depIdxs,
		MessageInfos:      file_pkg_agent_app_config_pb_config_proto_msgTypes,
	}.Build()
	File_pkg_agent_app_config_pb_config_proto = out.File
	file_pkg_agent_app_config_pb_config_proto_goTypes = nil
	file_pkg_agent_app_config_pb_config_proto_depIdxs = nil
}
