// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package mongodb

import (
	context "context"
	common "github.com/upmio/unit-operator/pkg/agent/app/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MongoDBOperationClient is the client API for MongoDBOperation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MongoDBOperationClient interface {
	Backup(ctx context.Context, in *BackupRequest, opts ...grpc.CallOption) (*common.Empty, error)
	Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*common.Empty, error)
	SetVariable(ctx context.Context, in *SetVariableRequest, opts ...grpc.CallOption) (*common.Empty, error)
}

type mongoDBOperationClient struct {
	cc grpc.ClientConnInterface
}

func NewMongoDBOperationClient(cc grpc.ClientConnInterface) MongoDBOperationClient {
	return &mongoDBOperationClient{cc}
}

func (c *mongoDBOperationClient) Backup(ctx context.Context, in *BackupRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/mongodb.MongoDBOperation/Backup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mongoDBOperationClient) Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/mongodb.MongoDBOperation/Restore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mongoDBOperationClient) SetVariable(ctx context.Context, in *SetVariableRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/mongodb.MongoDBOperation/SetVariable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MongoDBOperationServer is the server API for MongoDBOperation service.
// All implementations must embed UnimplementedMongoDBOperationServer
// for forward compatibility
type MongoDBOperationServer interface {
	Backup(context.Context, *BackupRequest) (*common.Empty, error)
	Restore(context.Context, *RestoreRequest) (*common.Empty, error)
	SetVariable(context.Context, *SetVariableRequest) (*common.Empty, error)
	mustEmbedUnimplementedMongoDBOperationServer()
}

// UnimplementedMongoDBOperationServer must be embedded to have forward compatible implementations.
type UnimplementedMongoDBOperationServer struct {
}

func (UnimplementedMongoDBOperationServer) Backup(context.Context, *BackupRequest) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Backup not implemented")
}
func (UnimplementedMongoDBOperationServer) Restore(context.Context, *RestoreRequest) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Restore not implemented")
}
func (UnimplementedMongoDBOperationServer) SetVariable(context.Context, *SetVariableRequest) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetVariable not implemented")
}
func (UnimplementedMongoDBOperationServer) mustEmbedUnimplementedMongoDBOperationServer() {}

// UnsafeMongoDBOperationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MongoDBOperationServer will
// result in compilation errors.
type UnsafeMongoDBOperationServer interface {
	mustEmbedUnimplementedMongoDBOperationServer()
}

func RegisterMongoDBOperationServer(s grpc.ServiceRegistrar, srv MongoDBOperationServer) {
	s.RegisterService(&MongoDBOperation_ServiceDesc, srv)
}

func _MongoDBOperation_Backup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MongoDBOperationServer).Backup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mongodb.MongoDBOperation/Backup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MongoDBOperationServer).Backup(ctx, req.(*BackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MongoDBOperation_Restore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MongoDBOperationServer).Restore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mongodb.MongoDBOperation/Restore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MongoDBOperationServer).Restore(ctx, req.(*RestoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MongoDBOperation_SetVariable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetVariableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MongoDBOperationServer).SetVariable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mongodb.MongoDBOperation/SetVariable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MongoDBOperationServer).SetVariable(ctx, req.(*SetVariableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MongoDBOperation_ServiceDesc is the grpc.ServiceDesc for MongoDBOperation service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MongoDBOperation_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mongodb.MongoDBOperation",
	HandlerType: (*MongoDBOperationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Backup",
			Handler:    _MongoDBOperation_Backup_Handler,
		},
		{
			MethodName: "Restore",
			Handler:    _MongoDBOperation_Restore_Handler,
		},
		{
			MethodName: "SetVariable",
			Handler:    _MongoDBOperation_SetVariable_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/agent/app/mongodb/pb/mongodb.proto",
}
