// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.0
// source: pkg/agent/app/mongodb/pb/mongodb.proto

package mongodb

import (
	common "github.com/upmio/unit-operator/pkg/agent/app/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BackupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BackupFile    string                 `protobuf:"bytes,1,opt,name=backup_file,json=backupFile,proto3" json:"backup_file,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	ObjectStorage *common.ObjectStorage  `protobuf:"bytes,3,opt,name=object_storage,json=objectStorage,proto3" json:"object_storage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupRequest) Reset() {
	*x = BackupRequest{}
	mi := &file_pkg_agent_app_mongodb_pb_mongodb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupRequest) ProtoMessage() {}

func (x *BackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_app_mongodb_pb_mongodb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupRequest.ProtoReflect.Descriptor instead.
func (*BackupRequest) Descriptor() ([]byte, []int) {
	return file_pkg_agent_app_mongodb_pb_mongodb_proto_rawDescGZIP(), []int{0}
}

func (x *BackupRequest) GetBackupFile() string {
	if x != nil {
		return x.BackupFile
	}
	return ""
}

func (x *BackupRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *BackupRequest) GetObjectStorage() *common.ObjectStorage {
	if x != nil {
		return x.ObjectStorage
	}
	return nil
}

type RestoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BackupFile    string                 `protobuf:"bytes,1,opt,name=backup_file,json=backupFile,proto3" json:"backup_file,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	ObjectStorage *common.ObjectStorage  `protobuf:"bytes,3,opt,name=object_storage,json=objectStorage,proto3" json:"object_storage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreRequest) Reset() {
	*x = RestoreRequest{}
	mi := &file_pkg_agent_app_mongodb_pb_mongodb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreRequest) ProtoMessage() {}

func (x *RestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_app_mongodb_pb_mongodb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreRequest.ProtoReflect.Descriptor instead.
func (*RestoreRequest) Descriptor() ([]byte, []int) {
	return file_pkg_agent_app_mongodb_pb_mongodb_proto_rawDescGZIP(), []int{1}
}

func (x *RestoreRequest) GetBackupFile() string {
	if x != nil {
		return x.BackupFile
	}
	return ""
}

func (x *RestoreRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RestoreRequest) GetObjectStorage() *common.ObjectStorage {
	if x != nil {
		return x.ObjectStorage
	}
	return nil
}

type SetVariableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"` // "bool" | "int" | "string" | "float"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetVariableRequest) Reset() {
	*x = SetVariableRequest{}
	mi := &file_pkg_agent_app_mongodb_pb_mongodb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetVariableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetVariableRequest) ProtoMessage() {}

func (x *SetVariableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_app_mongodb_pb_mongodb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetVariableRequest.ProtoReflect.Descriptor instead.
func (*SetVariableRequest) Descriptor() ([]byte, []int) {
	return file_pkg_agent_app_mongodb_pb_mongodb_proto_rawDescGZIP(), []int{2}
}

func (x *SetVariableRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetVariableRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SetVariableRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SetVariableRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

var File_pkg_agent_app_mongodb_pb_mongodb_proto protoreflect.FileDescriptor

const file_pkg_agent_app_mongodb_pb_mongodb_proto_rawDesc = "" +
	"\n" +
	"&pkg/agent/app/mongodb/pb/mongodb.proto\x12\amongodb\x1a$pkg/agent/app/common/pb/common.proto\"\x8a\x01\n" +
	"\rBackupRequest\x12\x1f\n" +
	"\vbackup_file\x18\x01 \x01(\tR\n" +
	"backupFile\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12<\n" +
	"\x0eobject_storage\x18\x03 \x01(\v2\x15.common.ObjectStorageR\robjectStorage\"\x8b\x01\n" +
	"\x0eRestoreRequest\x12\x1f\n" +
	"\vbackup_file\x18\x01 \x01(\tR\n" +
	"backupFile\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12<\n" +
	"\x0eobject_storage\x18\x03 \x01(\v2\x15.common.ObjectStorageR\robjectStorage\"l\n" +
	"\x12SetVariableRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type2\xb1\x01\n" +
	"\x10MongoDBOperation\x12/\n" +
	"\x06Backup\x12\x16.mongodb.BackupRequest\x1a\r.common.Empty\x121\n" +
	"\aRestore\x12\x17.mongodb.RestoreRequest\x1a\r.common.Empty\x129\n" +
	"\vSetVariable\x12\x1b.mongodb.SetVariableRequest\x1a\r.common.EmptyB6Z4github.com/upmio/unit-operator/pkg/agent/app/mongodbb\x06proto3"

var (
	file_pkg_agent_app_mongodb_pb_mongodb_proto_rawDescOnce sync.Once
	file_pkg_agent_app_mongodb_pb_mongodb_proto_rawDescData []byte
)

func file_pkg_agent_app_mongodb_pb_mongodb_proto_rawDescGZIP() []byte {
	file_pkg_agent_app_mongodb_pb_mongodb_proto_rawDescOnce.Do(func() {
		file_pkg_agent_app_mongodb_pb_mongodb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_agent_app_mongodb_pb_mongodb_proto_rawDesc), len(file_pkg_agent_app_mongodb_pb_mongodb_proto_rawDesc)))
	})
	return file_pkg_agent_app_mongodb_pb_mongodb_proto_rawDescData
}

var file_pkg_agent_app_mongodb_pb_mongodb_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_agent_app_mongodb_pb_mongodb_proto_goTypes = []any{
	(*BackupRequest)(nil),        // 0: mongodb.BackupRequest
	(*RestoreRequest)(nil),       // 1: mongodb.RestoreRequest
	(*SetVariableRequest)(nil),   // 2: mongodb.SetVariableRequest
	(*common.ObjectStorage)(nil), // 3: common.ObjectStorage
	(*common.Empty)(nil),         // 4: common.Empty
}
var file_pkg_agent_app_mongodb_pb_mongodb_proto_depIdxs = []int32{
	3, // 0: mongodb.BackupRequest.object_storage:type_name -> common.ObjectStorage
	3, // 1: mongodb.RestoreRequest.object_storage:type_name -> common.ObjectStorage
	0, // 2: mongodb.MongoDBOperation.Backup:input_type -> mongodb.BackupRequest
	1, // 3: mongodb.MongoDBOperation.Restore:input_type -> mongodb.RestoreRequest
	2, // 4: mongodb.MongoDBOperation.SetVariable:input_type -> mongodb.SetVariableRequest
	4, // 5: mongodb.MongoDBOperation.Backup:output_type -> common.Empty
	4, // 6: mongodb.MongoDBOperation.Restore:output_type -> common.Empty
	4, // 7: mongodb.MongoDBOperation.SetVariable:output_type -> common.Empty
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_agent_app_mongodb_pb_mongodb_proto_init() }
func file_pkg_agent_app_mongodb_pb_mongodb_proto_init() {
	if File_pkg_agent_app_mongodb_pb_mongodb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_agent_app_mongodb_pb_mongodb_proto_rawDesc), len(file_pkg_agent_app_mongodb_pb_mongodb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_agent_app_mongodb_pb_mongodb_proto_goTypes,
		DependencyIndexes: file_pkg_agent_app_mongodb_pb_mongodb_proto_depIdxs,
		MessageInfos:      file_pkg_agent_app_mongodb_pb_mongodb_proto_msgTypes,
	}.Build()
	File_pkg_agent_app_mongodb_pb_mongodb_proto = out.File
	file_pkg_agent_app_mongodb_pb_mongodb_proto_goTypes = nil
	file_pkg_agent_app_mongodb_pb_mongodb_proto_depIdxs = nil
}
