// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.0
// source: pkg/agent/app/milvus/pb/milvus.proto

package milvus

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type S3Storage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      string                 `protobuf:"bytes,1,opt,name=Endpoint,proto3" json:"Endpoint,omitempty"`
	Bucket        string                 `protobuf:"bytes,2,opt,name=Bucket,proto3" json:"Bucket,omitempty"`
	AccessKey     string                 `protobuf:"bytes,3,opt,name=AccessKey,proto3" json:"AccessKey,omitempty"`
	SecretKey     string                 `protobuf:"bytes,4,opt,name=SecretKey,proto3" json:"SecretKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S3Storage) Reset() {
	*x = S3Storage{}
	mi := &file_pkg_agent_app_milvus_pb_milvus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S3Storage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S3Storage) ProtoMessage() {}

func (x *S3Storage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_app_milvus_pb_milvus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S3Storage.ProtoReflect.Descriptor instead.
func (*S3Storage) Descriptor() ([]byte, []int) {
	return file_pkg_agent_app_milvus_pb_milvus_proto_rawDescGZIP(), []int{0}
}

func (x *S3Storage) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *S3Storage) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *S3Storage) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *S3Storage) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

type BackupRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	S3Storage      *S3Storage             `protobuf:"bytes,1,opt,name=S3Storage,proto3" json:"S3Storage,omitempty"`
	BackupFile     string                 `protobuf:"bytes,2,opt,name=BackupFile,proto3" json:"BackupFile,omitempty"`
	BackupRootPath string                 `protobuf:"bytes,3,opt,name=BackupRootPath,proto3" json:"BackupRootPath,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BackupRequest) Reset() {
	*x = BackupRequest{}
	mi := &file_pkg_agent_app_milvus_pb_milvus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupRequest) ProtoMessage() {}

func (x *BackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_app_milvus_pb_milvus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupRequest.ProtoReflect.Descriptor instead.
func (*BackupRequest) Descriptor() ([]byte, []int) {
	return file_pkg_agent_app_milvus_pb_milvus_proto_rawDescGZIP(), []int{1}
}

func (x *BackupRequest) GetS3Storage() *S3Storage {
	if x != nil {
		return x.S3Storage
	}
	return nil
}

func (x *BackupRequest) GetBackupFile() string {
	if x != nil {
		return x.BackupFile
	}
	return ""
}

func (x *BackupRequest) GetBackupRootPath() string {
	if x != nil {
		return x.BackupRootPath
	}
	return ""
}

type RestoreRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	S3Storage      *S3Storage             `protobuf:"bytes,1,opt,name=S3Storage,proto3" json:"S3Storage,omitempty"`
	BackupFile     string                 `protobuf:"bytes,2,opt,name=BackupFile,proto3" json:"BackupFile,omitempty"`
	BackupRootPath string                 `protobuf:"bytes,3,opt,name=BackupRootPath,proto3" json:"BackupRootPath,omitempty"`
	Suffix         string                 `protobuf:"bytes,4,opt,name=Suffix,proto3" json:"Suffix,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RestoreRequest) Reset() {
	*x = RestoreRequest{}
	mi := &file_pkg_agent_app_milvus_pb_milvus_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreRequest) ProtoMessage() {}

func (x *RestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_app_milvus_pb_milvus_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreRequest.ProtoReflect.Descriptor instead.
func (*RestoreRequest) Descriptor() ([]byte, []int) {
	return file_pkg_agent_app_milvus_pb_milvus_proto_rawDescGZIP(), []int{2}
}

func (x *RestoreRequest) GetS3Storage() *S3Storage {
	if x != nil {
		return x.S3Storage
	}
	return nil
}

func (x *RestoreRequest) GetBackupFile() string {
	if x != nil {
		return x.BackupFile
	}
	return ""
}

func (x *RestoreRequest) GetBackupRootPath() string {
	if x != nil {
		return x.BackupRootPath
	}
	return ""
}

func (x *RestoreRequest) GetSuffix() string {
	if x != nil {
		return x.Suffix
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_pkg_agent_app_milvus_pb_milvus_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_app_milvus_pb_milvus_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_pkg_agent_app_milvus_pb_milvus_proto_rawDescGZIP(), []int{3}
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pkg_agent_app_milvus_pb_milvus_proto protoreflect.FileDescriptor

const file_pkg_agent_app_milvus_pb_milvus_proto_rawDesc = "" +
	"\n" +
	"$pkg/agent/app/milvus/pb/milvus.proto\x12\x06milvus\"{\n" +
	"\tS3Storage\x12\x1a\n" +
	"\bEndpoint\x18\x01 \x01(\tR\bEndpoint\x12\x16\n" +
	"\x06Bucket\x18\x02 \x01(\tR\x06Bucket\x12\x1c\n" +
	"\tAccessKey\x18\x03 \x01(\tR\tAccessKey\x12\x1c\n" +
	"\tSecretKey\x18\x04 \x01(\tR\tSecretKey\"\x88\x01\n" +
	"\rBackupRequest\x12/\n" +
	"\tS3Storage\x18\x01 \x01(\v2\x11.milvus.S3StorageR\tS3Storage\x12\x1e\n" +
	"\n" +
	"BackupFile\x18\x02 \x01(\tR\n" +
	"BackupFile\x12&\n" +
	"\x0eBackupRootPath\x18\x03 \x01(\tR\x0eBackupRootPath\"\xa1\x01\n" +
	"\x0eRestoreRequest\x12/\n" +
	"\tS3Storage\x18\x01 \x01(\v2\x11.milvus.S3StorageR\tS3Storage\x12\x1e\n" +
	"\n" +
	"BackupFile\x18\x02 \x01(\tR\n" +
	"BackupFile\x12&\n" +
	"\x0eBackupRootPath\x18\x03 \x01(\tR\x0eBackupRootPath\x12\x16\n" +
	"\x06Suffix\x18\x04 \x01(\tR\x06Suffix\"$\n" +
	"\bResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2y\n" +
	"\x0fMilvusOperation\x121\n" +
	"\x06Backup\x12\x15.milvus.BackupRequest\x1a\x10.milvus.Response\x123\n" +
	"\aRestore\x12\x16.milvus.RestoreRequest\x1a\x10.milvus.ResponseB5Z3github.com/upmio/unit-operator/pkg/agent/app/milvusb\x06proto3"

var (
	file_pkg_agent_app_milvus_pb_milvus_proto_rawDescOnce sync.Once
	file_pkg_agent_app_milvus_pb_milvus_proto_rawDescData []byte
)

func file_pkg_agent_app_milvus_pb_milvus_proto_rawDescGZIP() []byte {
	file_pkg_agent_app_milvus_pb_milvus_proto_rawDescOnce.Do(func() {
		file_pkg_agent_app_milvus_pb_milvus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_agent_app_milvus_pb_milvus_proto_rawDesc), len(file_pkg_agent_app_milvus_pb_milvus_proto_rawDesc)))
	})
	return file_pkg_agent_app_milvus_pb_milvus_proto_rawDescData
}

var file_pkg_agent_app_milvus_pb_milvus_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_agent_app_milvus_pb_milvus_proto_goTypes = []any{
	(*S3Storage)(nil),      // 0: milvus.S3Storage
	(*BackupRequest)(nil),  // 1: milvus.BackupRequest
	(*RestoreRequest)(nil), // 2: milvus.RestoreRequest
	(*Response)(nil),       // 3: milvus.Response
}
var file_pkg_agent_app_milvus_pb_milvus_proto_depIdxs = []int32{
	0, // 0: milvus.BackupRequest.S3Storage:type_name -> milvus.S3Storage
	0, // 1: milvus.RestoreRequest.S3Storage:type_name -> milvus.S3Storage
	1, // 2: milvus.MilvusOperation.Backup:input_type -> milvus.BackupRequest
	2, // 3: milvus.MilvusOperation.Restore:input_type -> milvus.RestoreRequest
	3, // 4: milvus.MilvusOperation.Backup:output_type -> milvus.Response
	3, // 5: milvus.MilvusOperation.Restore:output_type -> milvus.Response
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_agent_app_milvus_pb_milvus_proto_init() }
func file_pkg_agent_app_milvus_pb_milvus_proto_init() {
	if File_pkg_agent_app_milvus_pb_milvus_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_agent_app_milvus_pb_milvus_proto_rawDesc), len(file_pkg_agent_app_milvus_pb_milvus_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_agent_app_milvus_pb_milvus_proto_goTypes,
		DependencyIndexes: file_pkg_agent_app_milvus_pb_milvus_proto_depIdxs,
		MessageInfos:      file_pkg_agent_app_milvus_pb_milvus_proto_msgTypes,
	}.Build()
	File_pkg_agent_app_milvus_pb_milvus_proto = out.File
	file_pkg_agent_app_milvus_pb_milvus_proto_goTypes = nil
	file_pkg_agent_app_milvus_pb_milvus_proto_depIdxs = nil
}
